/*
 * Copyright (C) 2015-2022 Ole André Vadla Ravnås <oleavr@nowsecure.com>
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __HOOX_ARM_REG_H__
#define __HOOX_ARM_REG_H__

#include <hx_disasm.h>
#include "hooxdefs.h"

HX_BEGIN_DECLS

typedef hx_uint HooxArmMetaReg;
typedef struct _HooxArmRegInfo HooxArmRegInfo;

enum _HooxArmMetaReg
{
  HOOX_ARM_MREG_R0,
  HOOX_ARM_MREG_R1,
  HOOX_ARM_MREG_R2,
  HOOX_ARM_MREG_R3,
  HOOX_ARM_MREG_R4,
  HOOX_ARM_MREG_R5,
  HOOX_ARM_MREG_R6,
  HOOX_ARM_MREG_R7,
  HOOX_ARM_MREG_R8,
  HOOX_ARM_MREG_R9,
  HOOX_ARM_MREG_R10,
  HOOX_ARM_MREG_R11,
  HOOX_ARM_MREG_R12,
  HOOX_ARM_MREG_R13,
  HOOX_ARM_MREG_R14,
  HOOX_ARM_MREG_R15,

  HOOX_ARM_MREG_S0,
  HOOX_ARM_MREG_S1,
  HOOX_ARM_MREG_S2,
  HOOX_ARM_MREG_S3,
  HOOX_ARM_MREG_S4,
  HOOX_ARM_MREG_S5,
  HOOX_ARM_MREG_S6,
  HOOX_ARM_MREG_S7,
  HOOX_ARM_MREG_S8,
  HOOX_ARM_MREG_S9,
  HOOX_ARM_MREG_S10,
  HOOX_ARM_MREG_S11,
  HOOX_ARM_MREG_S12,
  HOOX_ARM_MREG_S13,
  HOOX_ARM_MREG_S14,
  HOOX_ARM_MREG_S15,
  HOOX_ARM_MREG_S16,
  HOOX_ARM_MREG_S17,
  HOOX_ARM_MREG_S18,
  HOOX_ARM_MREG_S19,
  HOOX_ARM_MREG_S20,
  HOOX_ARM_MREG_S21,
  HOOX_ARM_MREG_S22,
  HOOX_ARM_MREG_S23,
  HOOX_ARM_MREG_S24,
  HOOX_ARM_MREG_S25,
  HOOX_ARM_MREG_S26,
  HOOX_ARM_MREG_S27,
  HOOX_ARM_MREG_S28,
  HOOX_ARM_MREG_S29,
  HOOX_ARM_MREG_S30,
  HOOX_ARM_MREG_S31,

  HOOX_ARM_MREG_D0,
  HOOX_ARM_MREG_D1,
  HOOX_ARM_MREG_D2,
  HOOX_ARM_MREG_D3,
  HOOX_ARM_MREG_D4,
  HOOX_ARM_MREG_D5,
  HOOX_ARM_MREG_D6,
  HOOX_ARM_MREG_D7,
  HOOX_ARM_MREG_D8,
  HOOX_ARM_MREG_D9,
  HOOX_ARM_MREG_D10,
  HOOX_ARM_MREG_D11,
  HOOX_ARM_MREG_D12,
  HOOX_ARM_MREG_D13,
  HOOX_ARM_MREG_D14,
  HOOX_ARM_MREG_D15,
  HOOX_ARM_MREG_D16,
  HOOX_ARM_MREG_D17,
  HOOX_ARM_MREG_D18,
  HOOX_ARM_MREG_D19,
  HOOX_ARM_MREG_D20,
  HOOX_ARM_MREG_D21,
  HOOX_ARM_MREG_D22,
  HOOX_ARM_MREG_D23,
  HOOX_ARM_MREG_D24,
  HOOX_ARM_MREG_D25,
  HOOX_ARM_MREG_D26,
  HOOX_ARM_MREG_D27,
  HOOX_ARM_MREG_D28,
  HOOX_ARM_MREG_D29,
  HOOX_ARM_MREG_D30,
  HOOX_ARM_MREG_D31,

  HOOX_ARM_MREG_Q0,
  HOOX_ARM_MREG_Q1,
  HOOX_ARM_MREG_Q2,
  HOOX_ARM_MREG_Q3,
  HOOX_ARM_MREG_Q4,
  HOOX_ARM_MREG_Q5,
  HOOX_ARM_MREG_Q6,
  HOOX_ARM_MREG_Q7,
  HOOX_ARM_MREG_Q8,
  HOOX_ARM_MREG_Q9,
  HOOX_ARM_MREG_Q10,
  HOOX_ARM_MREG_Q11,
  HOOX_ARM_MREG_Q12,
  HOOX_ARM_MREG_Q13,
  HOOX_ARM_MREG_Q14,
  HOOX_ARM_MREG_Q15,

  HOOX_ARM_MREG_SP = HOOX_ARM_MREG_R13,
  HOOX_ARM_MREG_LR = HOOX_ARM_MREG_R14,

  HOOX_ARM_MREG_PC = HOOX_ARM_MREG_R15
};

struct _HooxArmRegInfo
{
  HooxArmMetaReg meta;
  hx_uint width;
  hx_uint index;
};

HOOX_API void hoox_arm_reg_describe (hx_arm_reg reg, HooxArmRegInfo * ri);

HX_END_DECLS

#endif
