#!/usr/bin/env python3
"""
hoox amalgamation tool.

Merges a set of C sources + headers into a single translation unit (and a
single public header), SQLite-style. Project-local includes (#include "x.h")
are inlined exactly once; system includes (#include <x>) are hoisted and
de-duplicated at the top.

Usage:
    amalgamate.py --out-c hoox.c [--out-h hoox.h] \
        --include-dir DIR [--include-dir DIR ...] \
        --header PUBLIC.h [...] \
        SOURCE.c [SOURCE.c ...]

The spike (M1.5 / T1.9) runs this over the compat layer to prove that the
extracted gum code (which is not written amalgamation-friendly) can be merged
into one TU without static-symbol / macro collisions.
"""

import argparse
import os
import re
import sys

INCLUDE_LOCAL = re.compile(r'^\s*#\s*include\s*"([^"]+)"\s*$')
INCLUDE_SYSTEM = re.compile(r'^\s*#\s*include\s*<([^>]+)>\s*$')
PRAGMA_ONCE = re.compile(r'^\s*#\s*pragma\s+once\s*$')


def find_header(name, include_dirs, current_dir):
    bases = ([current_dir] if current_dir is not None else []) + include_dirs
    for base in bases:
        cand = os.path.normpath(os.path.join(base, name))
        if os.path.isfile(cand):
            return cand
    return None


class Amalgamator:
    def __init__(self, include_dirs):
        self.include_dirs = include_dirs
        self.header_inlined = set()        # absolute paths already inlined
        self.out = []

    def inline_header(self, path):
        path = os.path.normpath(path)
        if path in self.header_inlined:
            return
        self.header_inlined.add(path)
        self.out.append("/* ==== inlined header: %s ==== */" %
                        os.path.basename(path))
        self._emit_file(path)

    def _emit_file(self, path):
        current_dir = os.path.dirname(path)
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                stripped = line.rstrip("\n")

                if PRAGMA_ONCE.match(stripped):
                    continue

                m = INCLUDE_SYSTEM.match(stripped)
                if m:
                    # An angle-bracket include that resolves within our own
                    # include dirs (e.g. the <capstone.h> shim) is a project
                    # header — inline it. A real system header is left in
                    # place (its own guard makes duplicates harmless, and this
                    # keeps includes inside #ifdef platform blocks intact).
                    hdr = find_header(m.group(1), self.include_dirs, None)
                    if hdr is not None:
                        self.inline_header(hdr)
                    else:
                        self.out.append(stripped)
                    continue

                m = INCLUDE_LOCAL.match(stripped)
                if m:
                    hdr = find_header(m.group(1), self.include_dirs,
                                      current_dir)
                    if hdr is not None:
                        self.inline_header(hdr)
                    else:
                        # Unknown local header: keep as-is (will fail loudly).
                        self.out.append(stripped)
                    continue

                self.out.append(stripped)

    def emit_source(self, path):
        self.out.append("")
        self.out.append("/* ==== source: %s ==== */" % os.path.basename(path))
        self._emit_file(path)

    def render(self, banner):
        parts = [banner, ""]
        parts.extend(self.out)
        parts.append("")
        return "\n".join(parts)


BANNER = """\
/*
 * hoox — amalgamated single-file build.
 *
 * Generated by tools/amalgamate.py. Do not edit by hand.
 *
 * Licence: wxWindows Library Licence, Version 3.1 (see COPYING).
 * Portions of the instruction decoder derive from Microsoft Detours (MIT);
 * see NOTICE.
 */"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-c", required=True)
    ap.add_argument("--out-h")
    ap.add_argument("--include-dir", action="append", default=[])
    ap.add_argument("--header", action="append", default=[],
                    help="public headers to inline first (into out-c, and "
                         "into out-h if given)")
    ap.add_argument("sources", nargs="+")
    args = ap.parse_args()

    inc = [os.path.abspath(d) for d in args.include_dir]

    # Single-TU source.
    a = Amalgamator(inc)
    for h in args.header:
        a.inline_header(os.path.abspath(h))
    for s in args.sources:
        a.emit_source(os.path.abspath(s))
    os.makedirs(os.path.dirname(os.path.abspath(args.out_c)), exist_ok=True)
    with open(args.out_c, "w", encoding="utf-8") as f:
        f.write(a.render(BANNER))
    print("wrote %s (%d headers inlined)" %
          (args.out_c, len(a.header_inlined)))

    # Public header (optional).
    if args.out_h and args.header:
        ah = Amalgamator(inc)
        for h in args.header:
            ah.inline_header(os.path.abspath(h))
        with open(args.out_h, "w", encoding="utf-8") as f:
            f.write(ah.render(BANNER))
        print("wrote %s" % args.out_h)

    return 0


if __name__ == "__main__":
    sys.exit(main())
