/*
 * hoox — amalgamated single-file build.
 *
 * Generated by tools/amalgamate.py. Do not edit by hand.
 *
 * Licence: wxWindows Library Licence, Version 3.1 (see COPYING).
 * Portions of the instruction decoder derive from Microsoft Detours (MIT);
 * see NOTICE.
 */

/* ==== inlined header: gum.h ==== */
/*
 * hoox — public umbrella header (trimmed frida-gum gum.h).
 *
 * Exposes the inline-hook surface: init/deinit plus the Interceptor,
 * invocation listener/context, and the memory API.
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __GUM_H__
#define __GUM_H__

/* ==== inlined header: gumdefs.h ==== */
/*
 * Copyright (C) 2008-2026 Ole André Vadla Ravnås <oleavr@nowsecure.com>
 * Copyright (C) 2023 Håvard Sørbø <havard@hsorbo.no>
 * Copyright (C) 2024 Yannis Juglaret <yjuglaret@mozilla.com>
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __GUMDEFS_H__
#define __GUMDEFS_H__

/* ==== inlined header: capstone.h ==== */
/*
 * hoox — capstone-compatible shim.
 *
 * hoox does not depend on capstone. This header provides the *subset* of
 * capstone's public x86 API that the extracted frida-gum hook engine uses,
 * so those sources compile with their `#include <capstone.h>` unchanged. It
 * is backed by a compact in-tree decoder (hx_disasm_x86.c) informed by
 * Microsoft Detours' relocation engine.
 *
 * Enum values need not match upstream capstone: the extracted code only ever
 * compares against these symbols (e.g. switch on X86_INS_JMP), so any set of
 * distinct values that the decoder and the consumers agree on is correct.
 *
 * Licence: wxWindows Library Licence, Version 3.1
 * Portions derive from Microsoft Detours (MIT); see NOTICE.
 */

#ifndef __HOOX_CAPSTONE_SHIM_H__
#define __HOOX_CAPSTONE_SHIM_H__

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef size_t csh;

typedef enum cs_arch
{
  CS_ARCH_X86 = 3,
} cs_arch;

typedef enum cs_mode
{
  CS_MODE_32 = 1 << 2,
  CS_MODE_64 = 1 << 3,
} cs_mode;

typedef enum cs_err
{
  CS_ERR_OK = 0,
  CS_ERR_MEM,
  CS_ERR_ARCH,
  CS_ERR_HANDLE,
} cs_err;

typedef enum cs_opt_type
{
  CS_OPT_DETAIL = 2,
  CS_OPT_MODE = 1,
  CS_OPT_MEM = 3,
} cs_opt_type;

typedef enum cs_opt_value
{
  CS_OPT_OFF = 0,
  CS_OPT_ON = 3,
} cs_opt_value;

/* ---- x86 registers ------------------------------------------------------ */

typedef enum x86_reg
{
  X86_REG_INVALID = 0,

  /* 64-bit GP */
  X86_REG_RAX, X86_REG_RCX, X86_REG_RDX, X86_REG_RBX,
  X86_REG_RSP, X86_REG_RBP, X86_REG_RSI, X86_REG_RDI,
  X86_REG_R8, X86_REG_R9, X86_REG_R10, X86_REG_R11,
  X86_REG_R12, X86_REG_R13, X86_REG_R14, X86_REG_R15,

  /* 32-bit GP */
  X86_REG_EAX, X86_REG_ECX, X86_REG_EDX, X86_REG_EBX,
  X86_REG_ESP, X86_REG_EBP, X86_REG_ESI, X86_REG_EDI,
  X86_REG_R8D, X86_REG_R9D, X86_REG_R10D, X86_REG_R11D,
  X86_REG_R12D, X86_REG_R13D, X86_REG_R14D, X86_REG_R15D,

  /* instruction pointer */
  X86_REG_EIP, X86_REG_RIP,

  /* segment */
  X86_REG_CS, X86_REG_DS, X86_REG_ES, X86_REG_FS, X86_REG_GS, X86_REG_SS,

  X86_REG_ENDING
} x86_reg;

/* ---- x86 instruction ids (only those the hook engine references) -------- */

typedef enum x86_insn
{
  X86_INS_INVALID = 0,

  X86_INS_CALL,
  X86_INS_JMP,
  X86_INS_RET,
  X86_INS_RETF,

  X86_INS_JCXZ, X86_INS_JECXZ, X86_INS_JRCXZ,
  X86_INS_JO, X86_INS_JNO, X86_INS_JB, X86_INS_JAE,
  X86_INS_JE, X86_INS_JNE, X86_INS_JBE, X86_INS_JA,
  X86_INS_JS, X86_INS_JNS, X86_INS_JP, X86_INS_JNP,
  X86_INS_JL, X86_INS_JGE, X86_INS_JLE, X86_INS_JG,
  X86_INS_LOOP, X86_INS_LOOPE, X86_INS_LOOPNE,

  X86_INS_CMPXCHG,
  X86_INS_PUSH, X86_INS_POP,
  X86_INS_INT, X86_INS_INT3,
  X86_INS_SYSCALL, X86_INS_SYSENTER,
  X86_INS_NOP,

  /* common data-processing ids some relocator/reader/test paths switch on */
  X86_INS_MOV, X86_INS_LEA,
  X86_INS_ADD, X86_INS_OR, X86_INS_ADC, X86_INS_SBB,
  X86_INS_AND, X86_INS_SUB, X86_INS_XOR, X86_INS_CMP,
  X86_INS_TEST, X86_INS_INC, X86_INS_DEC,

  X86_INS_OTHER,   /* any instruction not individually classified */

  X86_INS_ENDING
} x86_insn;

/* ---- operands ----------------------------------------------------------- */

typedef enum x86_op_type
{
  X86_OP_INVALID = 0,
  X86_OP_REG,
  X86_OP_IMM,
  X86_OP_MEM,
} x86_op_type;

typedef struct x86_op_mem
{
  x86_reg segment;
  x86_reg base;
  x86_reg index;
  int scale;
  int64_t disp;
} x86_op_mem;

typedef struct cs_x86_op
{
  x86_op_type type;
  union
  {
    x86_reg reg;
    int64_t imm;
    x86_op_mem mem;
  };
  uint8_t size;
} cs_x86_op;

typedef struct cs_x86_encoding
{
  uint8_t modrm_offset;
  uint8_t disp_offset;
  uint8_t disp_size;
  uint8_t imm_offset;
  uint8_t imm_size;
} cs_x86_encoding;

#define CS_X86_MAX_OPS 4

typedef struct cs_x86
{
  uint8_t prefix[4];
  uint8_t opcode[4];
  uint8_t rex;
  uint8_t addr_size;
  uint8_t modrm;
  uint8_t sib;
  int64_t disp;
  cs_x86_encoding encoding;

  uint8_t op_count;
  cs_x86_op operands[CS_X86_MAX_OPS];
} cs_x86;

typedef struct cs_detail
{
  uint16_t regs_read[16];
  uint8_t regs_read_count;
  uint16_t regs_write[20];
  uint8_t regs_write_count;

  union
  {
    cs_x86 x86;
  };
} cs_detail;

typedef struct cs_insn
{
  unsigned int id;
  uint64_t address;
  uint16_t size;
  uint8_t bytes[24];
  char mnemonic[32];
  char op_str[160];
  cs_detail * detail;
} cs_insn;

typedef uint16_t cs_regs[64];

/* ---- API ---------------------------------------------------------------- */

cs_err cs_open (cs_arch arch, cs_mode mode, csh * handle);
cs_err cs_close (csh * handle);
cs_err cs_option (csh handle, cs_opt_type type, size_t value);

cs_insn * cs_malloc (csh handle);
void cs_free (cs_insn * insn, size_t count);

bool cs_disasm_iter (csh handle, const uint8_t ** code, size_t * size,
    uint64_t * address, cs_insn * insn);
size_t cs_disasm (csh handle, const uint8_t * code, size_t code_size,
    uint64_t address, size_t count, cs_insn ** insn);

bool cs_reg_read (csh handle, const cs_insn * insn, unsigned int reg_id);
bool cs_reg_write (csh handle, const cs_insn * insn, unsigned int reg_id);

void cs_arch_register_x86 (void);

#ifdef __cplusplus
}
#endif

#endif
/* ==== inlined header: hxglib.h ==== */
/*
 * hoox nano-glib: umbrella header.
 *
 * Extracted frida-gum sources include this in place of <glib.h>. It pulls in
 * the full GLib-compatible surface hoox reimplements (types, macros, memory,
 * atomics, threading, containers, strings) — with no external dependency.
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __HOOX_COMPAT_GLIB_H__
#define __HOOX_COMPAT_GLIB_H__

/* ==== inlined header: hxdefs.h ==== */
/*
 * hoox nano-glib: fundamental types and utility macros.
 *
 * A tiny, dependency-free reimplementation of the subset of GLib's
 * types/macros that the extracted frida-gum hook engine relies on. The
 * public surface intentionally keeps GLib's names (gint, gpointer,
 * G_BEGIN_DECLS, MIN/MAX, ...) so that extracted gum code compiles with only
 * its <glib.h> include swapped for <hxglib.h>.
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __HOOX_COMPAT_DEFS_H__
#define __HOOX_COMPAT_DEFS_H__

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <limits.h>

#ifdef __cplusplus
# define G_BEGIN_DECLS extern "C" {
# define G_END_DECLS }
#else
# define G_BEGIN_DECLS
# define G_END_DECLS
#endif

/* Platform detection macros (GLib-style) that extracted gum code expects. */
#if defined (_WIN32) && !defined (G_OS_WIN32)
# define G_OS_WIN32 1
#endif
#if !defined (_WIN32) && !defined (G_OS_UNIX)
# define G_OS_UNIX 1
#endif

G_BEGIN_DECLS

/* ---- fundamental types -------------------------------------------------- */

typedef int             gint;
typedef unsigned int    guint;
typedef short           gshort;
typedef unsigned short  gushort;
typedef long            glong;
typedef unsigned long   gulong;
typedef char            gchar;
typedef unsigned char   guchar;
typedef int             gboolean;

typedef int8_t          gint8;
typedef uint8_t         guint8;
typedef int16_t         gint16;
typedef uint16_t        guint16;
typedef int32_t         gint32;
typedef uint32_t        guint32;
typedef int64_t         gint64;
typedef uint64_t        guint64;

typedef float           gfloat;
typedef double          gdouble;

typedef size_t          gsize;
typedef ptrdiff_t       gssize;
typedef intptr_t        gintptr;
typedef uintptr_t       guintptr;
typedef gint64          goffset;

typedef void *          gpointer;
typedef const void *    gconstpointer;

typedef guint32         gunichar;

/* GObject/GLib type-system stand-ins: the hook path never registers or uses
 * these, but extracted declarations reference the typedefs. */
typedef guint32         GQuark;
typedef gsize           GType;
typedef struct _GError  GError;   /* opaque; only pointer decls survive */

/* ---- callback typedefs -------------------------------------------------- */

typedef void     (* GDestroyNotify) (gpointer data);
typedef void     (* GFreeFunc)      (gpointer data);
typedef guint    (* GHashFunc)      (gconstpointer key);
typedef gboolean (* GEqualFunc)     (gconstpointer a, gconstpointer b);
typedef gint     (* GCompareFunc)   (gconstpointer a, gconstpointer b);
typedef gint     (* GCompareDataFunc) (gconstpointer a, gconstpointer b,
                                       gpointer user_data);
typedef void     (* GFunc)          (gpointer data, gpointer user_data);
typedef void     (* GHFunc)         (gpointer key, gpointer value,
                                     gpointer user_data);
typedef gboolean (* GHRFunc)        (gpointer key, gpointer value,
                                     gpointer user_data);
typedef gpointer (* GCopyFunc)      (gconstpointer src, gpointer data);
typedef void     (* GCallback)      (void);

/* ---- truth values ------------------------------------------------------- */

#ifndef FALSE
# define FALSE (0)
#endif
#ifndef TRUE
# define TRUE (!FALSE)
#endif
#ifndef NULL
# define NULL ((void *) 0)
#endif

/* ---- limits ------------------------------------------------------------- */

#define G_MININT8   INT8_MIN
#define G_MAXINT8   INT8_MAX
#define G_MAXUINT8  UINT8_MAX
#define G_MININT16  INT16_MIN
#define G_MAXINT16  INT16_MAX
#define G_MAXUINT16 UINT16_MAX
#define G_MININT32  INT32_MIN
#define G_MAXINT32  INT32_MAX
#define G_MAXUINT32 UINT32_MAX
#define G_MININT64  INT64_MIN
#define G_MAXINT64  INT64_MAX
#define G_MAXUINT64 UINT64_MAX
#define G_MININT    INT_MIN
#define G_MAXINT    INT_MAX
#define G_MAXUINT   UINT_MAX
#define G_MINLONG   LONG_MIN
#define G_MAXLONG   LONG_MAX
#define G_MAXULONG  ULONG_MAX
#define G_MAXSIZE   SIZE_MAX
#define G_MAXSSIZE  PTRDIFF_MAX
#define G_MINSSIZE  PTRDIFF_MIN

#define G_GINT64_CONSTANT(val)  (val##LL)
#define G_GUINT64_CONSTANT(val) (val##ULL)

/* ---- pointer size / endianness ------------------------------------------ */

#if UINTPTR_MAX == 0xffffffffffffffffull
# define GLIB_SIZEOF_VOID_P 8
#else
# define GLIB_SIZEOF_VOID_P 4
#endif

#define G_LITTLE_ENDIAN 1234
#define G_BIG_ENDIAN    4321

#if defined (__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
# define G_BYTE_ORDER G_BIG_ENDIAN
#else
# define G_BYTE_ORDER G_LITTLE_ENDIAN
#endif

/* ---- format modifiers --------------------------------------------------- */

#define G_GINT64_MODIFIER  "ll"
#define G_GUINT64_FORMAT   "llu"
#define G_GINT64_FORMAT    "lld"
#if GLIB_SIZEOF_VOID_P == 8
# define G_GSIZE_MODIFIER  "ll"
# define G_GSIZE_FORMAT    "llu"
# define G_GSSIZE_FORMAT   "lld"
#else
# define G_GSIZE_MODIFIER  ""
# define G_GSIZE_FORMAT    "u"
# define G_GSSIZE_FORMAT   "d"
#endif

/* ---- compiler attributes ------------------------------------------------ */

#if defined (__GNUC__) || defined (__clang__)
# define G_GNUC_UNUSED            __attribute__ ((__unused__))
# define G_GNUC_NORETURN          __attribute__ ((__noreturn__))
# define G_GNUC_CONST             __attribute__ ((__const__))
# define G_GNUC_PURE              __attribute__ ((__pure__))
# define G_GNUC_WARN_UNUSED_RESULT __attribute__ ((__warn_unused_result__))
# define G_GNUC_PRINTF(f, a)      __attribute__ ((__format__ (__printf__, f, a)))
# define G_GNUC_NULL_TERMINATED   __attribute__ ((__sentinel__))
# define G_GNUC_INTERNAL          __attribute__ ((__visibility__ ("hidden")))
# define G_LIKELY(expr)           (__builtin_expect (!!(expr), 1))
# define G_UNLIKELY(expr)         (__builtin_expect (!!(expr), 0))
# define G_GNUC_FALLTHROUGH       __attribute__ ((__fallthrough__))
# define G_ALIGNOF(t)             __alignof__ (t)
# define G_GNUC_ALIGNED(n)        __attribute__ ((__aligned__ (n)))
# define G_GNUC_PACKED            __attribute__ ((__packed__))
# define G_NORETURN               __attribute__ ((__noreturn__))
#else
# define G_GNUC_UNUSED
# define G_GNUC_NORETURN          __declspec (noreturn)
# define G_GNUC_CONST
# define G_GNUC_PURE
# define G_GNUC_WARN_UNUSED_RESULT
# define G_GNUC_PRINTF(f, a)
# define G_GNUC_NULL_TERMINATED
# define G_GNUC_INTERNAL
# define G_LIKELY(expr)           (expr)
# define G_UNLIKELY(expr)         (expr)
# define G_GNUC_FALLTHROUGH
# define G_ALIGNOF(t)             __alignof (t)
# define G_GNUC_ALIGNED(n)        __declspec (align (n))
# define G_GNUC_PACKED
# define G_NORETURN               __declspec (noreturn)
#endif

#define G_ANALYZER_NORETURN

/* ---- statement wrappers ------------------------------------------------- */

#define G_STMT_START do
#define G_STMT_END   while (0)

/* ---- misc utility macros ------------------------------------------------ */

#define G_N_ELEMENTS(arr) (sizeof (arr) / sizeof ((arr)[0]))
#define G_STRUCT_OFFSET(struct_type, member) offsetof (struct_type, member)
#define G_STRUCT_MEMBER_P(struct_p, offset) \
    ((gpointer) ((guint8 *) (struct_p) + (glong) (offset)))
#define G_STRUCT_MEMBER(member_type, struct_p, offset) \
    (*(member_type *) G_STRUCT_MEMBER_P ((struct_p), (offset)))

#ifndef MIN
# define MIN(a, b) (((a) < (b)) ? (a) : (b))
#endif
#ifndef MAX
# define MAX(a, b) (((a) > (b)) ? (a) : (b))
#endif
#ifndef ABS
# define ABS(a) (((a) < 0) ? -(a) : (a))
#endif
#ifndef CLAMP
# define CLAMP(x, low, high) (((x) > (high)) ? (high) : (((x) < (low)) ? (low) : (x)))
#endif

#define GPOINTER_TO_INT(p)   ((gint) (gintptr) (p))
#define GPOINTER_TO_UINT(p)  ((guint) (guintptr) (p))
#define GINT_TO_POINTER(i)   ((gpointer) (gintptr) (i))
#define GUINT_TO_POINTER(u)  ((gpointer) (guintptr) (u))
#define GPOINTER_TO_SIZE(p)  ((gsize) (p))
#define GSIZE_TO_POINTER(s)  ((gpointer) (gsize) (s))

#define G_STATIC_ASSERT(expr) \
    typedef char _GStaticAssert[(expr) ? 1 : -1] G_GNUC_UNUSED

/* Byte order: hoox targets are little-endian (x86/ARM/ARM64/MIPSEL), so the
 * LE conversions are identities; provide byte-swapping BE forms for
 * completeness. */
#if defined (__GNUC__) || defined (__clang__)
# define GUINT16_SWAP(v) __builtin_bswap16 (v)
# define GUINT32_SWAP(v) __builtin_bswap32 (v)
# define GUINT64_SWAP(v) __builtin_bswap64 (v)
#else
# define GUINT16_SWAP(v) _byteswap_ushort (v)
# define GUINT32_SWAP(v) _byteswap_ulong (v)
# define GUINT64_SWAP(v) _byteswap_uint64 (v)
#endif

#if G_BYTE_ORDER == G_LITTLE_ENDIAN
# define GUINT16_TO_LE(v)   ((guint16) (v))
# define GUINT32_TO_LE(v)   ((guint32) (v))
# define GUINT64_TO_LE(v)   ((guint64) (v))
# define GUINT16_TO_BE(v)   ((guint16) GUINT16_SWAP (v))
# define GUINT32_TO_BE(v)   ((guint32) GUINT32_SWAP (v))
# define GUINT64_TO_BE(v)   ((guint64) GUINT64_SWAP (v))
#else
# define GUINT16_TO_LE(v)   ((guint16) GUINT16_SWAP (v))
# define GUINT32_TO_LE(v)   ((guint32) GUINT32_SWAP (v))
# define GUINT64_TO_LE(v)   ((guint64) GUINT64_SWAP (v))
# define GUINT16_TO_BE(v)   ((guint16) (v))
# define GUINT32_TO_BE(v)   ((guint32) (v))
# define GUINT64_TO_BE(v)   ((guint64) (v))
#endif
#define GUINT16_FROM_LE(v)  GUINT16_TO_LE (v)
#define GUINT32_FROM_LE(v)  GUINT32_TO_LE (v)
#define GUINT64_FROM_LE(v)  GUINT64_TO_LE (v)
#define GINT16_TO_LE(v)     ((gint16) GUINT16_TO_LE ((guint16) (v)))
#define GINT32_TO_LE(v)     ((gint32) GUINT32_TO_LE ((guint32) (v)))
#define GINT64_TO_LE(v)     ((gint64) GUINT64_TO_LE ((guint64) (v)))
#define GINT16_FROM_LE(v)   GINT16_TO_LE (v)
#define GINT32_FROM_LE(v)   GINT32_TO_LE (v)
#define GINT64_FROM_LE(v)   GINT64_TO_LE (v)

#define g_alloca(n) __builtin_alloca (n)

#define G_STRINGIFY(macro_or_string) G_STRINGIFY_ARG (macro_or_string)
#define G_STRINGIFY_ARG(contents) #contents

/* g_steal_pointer / g_clear_pointer live with the memory helpers but the
 * inline forms are handy from headers, so declare them here. */
static inline gpointer
g_steal_pointer (gpointer pp)
{
  gpointer * ptr = (gpointer *) pp;
  gpointer ref = *ptr;
  *ptr = NULL;
  return ref;
}

G_END_DECLS

#endif
/* ==== inlined header: hxmessages.h ==== */
/*
 * hoox nano-glib: assertions and logging.
 *
 * Minimal replacements for g_assert / g_return_* / g_warning etc. Logging is
 * routed to stderr; fatal paths abort(). No GLib log domains.
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __HOOX_COMPAT_MESSAGES_H__
#define __HOOX_COMPAT_MESSAGES_H__


#include <stdio.h>
#include <stdlib.h>

G_BEGIN_DECLS

#define g_error(...) \
    G_STMT_START { \
      fprintf (stderr, "** ERROR: " __VA_ARGS__); \
      fprintf (stderr, "\n"); \
      abort (); \
    } G_STMT_END

#define g_critical(...) \
    G_STMT_START { \
      fprintf (stderr, "** CRITICAL: " __VA_ARGS__); \
      fprintf (stderr, "\n"); \
    } G_STMT_END

#define g_warning(...) \
    G_STMT_START { \
      fprintf (stderr, "** WARNING: " __VA_ARGS__); \
      fprintf (stderr, "\n"); \
    } G_STMT_END

#define g_message(...) \
    G_STMT_START { \
      fprintf (stderr, __VA_ARGS__); \
      fprintf (stderr, "\n"); \
    } G_STMT_END

#define g_debug(...)   G_STMT_START { } G_STMT_END
#define g_info(...)    G_STMT_START { } G_STMT_END
#define g_print(...)   ((void) fprintf (stdout, __VA_ARGS__))
#define g_printerr(...) ((void) fprintf (stderr, __VA_ARGS__))

#define g_assert(expr) \
    G_STMT_START { \
      if (G_UNLIKELY (!(expr))) \
      { \
        fprintf (stderr, "%s:%d: assertion failed: %s\n", \
            __FILE__, __LINE__, #expr); \
        abort (); \
      } \
    } G_STMT_END

#define g_abort() abort ()

#define g_assert_not_reached() \
    G_STMT_START { \
      fprintf (stderr, "%s:%d: code should not be reached\n", \
          __FILE__, __LINE__); \
      abort (); \
    } G_STMT_END

#define g_assert_true(expr)   g_assert ((expr))
#define g_assert_false(expr)  g_assert (!(expr))
#define g_assert_null(expr)   g_assert ((expr) == NULL)
#define g_assert_nonnull(expr) g_assert ((expr) != NULL)

#define g_assert_cmpint(a, op, b)  g_assert ((a) op (b))
#define g_assert_cmpuint(a, op, b) g_assert ((a) op (b))
#define g_assert_cmphex(a, op, b)  g_assert ((a) op (b))
#define g_assert_cmpstr(a, op, b)  g_assert (strcmp ((a), (b)) op 0)
#define g_assert_cmpptr(a, op, b)  g_assert ((a) op (b))

#define g_return_if_fail(expr) \
    G_STMT_START { \
      if (G_UNLIKELY (!(expr))) \
      { \
        fprintf (stderr, "%s:%d: assertion '%s' failed\n", \
            __FILE__, __LINE__, #expr); \
        return; \
      } \
    } G_STMT_END

#define g_return_val_if_fail(expr, val) \
    G_STMT_START { \
      if (G_UNLIKELY (!(expr))) \
      { \
        fprintf (stderr, "%s:%d: assertion '%s' failed\n", \
            __FILE__, __LINE__, #expr); \
        return (val); \
      } \
    } G_STMT_END

#define g_return_if_reached() \
    G_STMT_START { \
      fprintf (stderr, "%s:%d: should not be reached\n", __FILE__, __LINE__); \
      return; \
    } G_STMT_END

#define g_return_val_if_reached(val) \
    G_STMT_START { \
      fprintf (stderr, "%s:%d: should not be reached\n", __FILE__, __LINE__); \
      return (val); \
    } G_STMT_END

/* GError: the hook path never surfaces errors this way. Provide no-op
 * stand-ins so extracted code that calls g_set_error still compiles. */
#define g_set_error(err, domain, code, ...)      ((void) 0)
#define g_set_error_literal(err, domain, code, m) ((void) 0)
#define g_clear_error(err)                        ((void) 0)
#define g_error_free(err)                         ((void) 0)
#define g_propagate_error(dest, src)              ((void) 0)

G_END_DECLS

#endif
/* ==== inlined header: hxmem.h ==== */
/*
 * hoox nano-glib: memory allocation.
 *
 * g_malloc/g_free family + g_slice_* (mapped to plain malloc/free) + g_new
 * helpers + g_memdup. Allocation failure aborts, matching GLib's g_malloc
 * contract (callers never check for NULL).
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __HOOX_COMPAT_MEM_H__
#define __HOOX_COMPAT_MEM_H__


G_BEGIN_DECLS

gpointer g_malloc (gsize n_bytes);
gpointer g_malloc0 (gsize n_bytes);
gpointer g_realloc (gpointer mem, gsize n_bytes);
gpointer g_try_malloc (gsize n_bytes);
gpointer g_try_malloc0 (gsize n_bytes);
void g_free (gpointer mem);

gpointer g_memdup (gconstpointer mem, guint byte_size);
gpointer g_memdup2 (gconstpointer mem, gsize byte_size);

/* g_slice_* : GLib's slab allocator is deprecated; map to malloc/free. */
gpointer g_slice_alloc (gsize block_size);
gpointer g_slice_alloc0 (gsize block_size);
gpointer g_slice_copy (gsize block_size, gconstpointer mem_block);
void g_slice_free1 (gsize block_size, gpointer mem_block);

#define g_newa(type, count) \
    ((type *) __builtin_alloca (sizeof (type) * (gsize) (count)))

#define g_new(type, count)   ((type *) g_malloc (sizeof (type) * (gsize) (count)))
#define g_new0(type, count)  ((type *) g_malloc0 (sizeof (type) * (gsize) (count)))
#define g_renew(type, mem, count) \
    ((type *) g_realloc ((mem), sizeof (type) * (gsize) (count)))

#define g_slice_new(type)    ((type *) g_slice_alloc (sizeof (type)))
#define g_slice_new0(type)   ((type *) g_slice_alloc0 (sizeof (type)))
#define g_slice_dup(type, mem) \
    ((type *) g_slice_copy (sizeof (type), (mem)))
#define g_slice_free(type, mem) g_slice_free1 (sizeof (type), (mem))

#define g_clear_pointer(pp, destroy) \
    G_STMT_START { \
      gpointer * _pp = (gpointer *) (pp); \
      gpointer _p = *_pp; \
      if (_p != NULL) \
      { \
        *_pp = NULL; \
        (destroy) (_p); \
      } \
    } G_STMT_END

G_END_DECLS

#endif
/* ==== inlined header: hxatomic.h ==== */
/*
 * hoox nano-glib: atomics.
 *
 * g_atomic_int_* / g_atomic_pointer_* over plain (non-_Atomic-qualified)
 * memory, matching GLib's contract. Backed by __atomic builtins on
 * clang/gcc and by _Interlocked* intrinsics on MSVC. Full sequential
 * consistency is used throughout (conservative; correct for the interceptor's
 * lock-free listener-entry COW).
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __HOOX_COMPAT_ATOMIC_H__
#define __HOOX_COMPAT_ATOMIC_H__


G_BEGIN_DECLS

#if defined (__GNUC__) || defined (__clang__)

static inline gint
g_atomic_int_get (const volatile gint * atomic)
{
  return __atomic_load_n (atomic, __ATOMIC_SEQ_CST);
}

static inline void
g_atomic_int_set (volatile gint * atomic,
                  gint newval)
{
  __atomic_store_n (atomic, newval, __ATOMIC_SEQ_CST);
}

static inline void
g_atomic_int_inc (volatile gint * atomic)
{
  (void) __atomic_fetch_add (atomic, 1, __ATOMIC_SEQ_CST);
}

static inline gboolean
g_atomic_int_dec_and_test (volatile gint * atomic)
{
  return __atomic_fetch_sub (atomic, 1, __ATOMIC_SEQ_CST) == 1;
}

static inline gint
g_atomic_int_add (volatile gint * atomic,
                  gint val)
{
  return __atomic_fetch_add (atomic, val, __ATOMIC_SEQ_CST);
}

static inline gboolean
g_atomic_int_compare_and_exchange (volatile gint * atomic,
                                   gint oldval,
                                   gint newval)
{
  return __atomic_compare_exchange_n (atomic, &oldval, newval, 0,
      __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST);
}

#define g_atomic_pointer_get(atomic) \
    __atomic_load_n ((atomic), __ATOMIC_SEQ_CST)
#define g_atomic_pointer_set(atomic, newval) \
    __atomic_store_n ((atomic), (newval), __ATOMIC_SEQ_CST)
#define g_atomic_pointer_compare_and_exchange(atomic, oldval, newval) \
    __extension__ ({ \
      __typeof__ (*(atomic)) _hx_old = (oldval); \
      __atomic_compare_exchange_n ((atomic), &_hx_old, (newval), 0, \
          __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST); \
    })

#else /* MSVC */

# include <intrin.h>

static inline gint
g_atomic_int_get (const volatile gint * atomic)
{
  gint v = *atomic;
  _ReadWriteBarrier ();
  return v;
}

static inline void
g_atomic_int_set (volatile gint * atomic,
                  gint newval)
{
  _ReadWriteBarrier ();
  *atomic = newval;
  _ReadWriteBarrier ();
}

static inline void
g_atomic_int_inc (volatile gint * atomic)
{
  (void) _InterlockedIncrement ((volatile long *) atomic);
}

static inline gboolean
g_atomic_int_dec_and_test (volatile gint * atomic)
{
  return _InterlockedDecrement ((volatile long *) atomic) == 0;
}

static inline gint
g_atomic_int_add (volatile gint * atomic,
                  gint val)
{
  return _InterlockedExchangeAdd ((volatile long *) atomic, val);
}

static inline gboolean
g_atomic_int_compare_and_exchange (volatile gint * atomic,
                                   gint oldval,
                                   gint newval)
{
  return _InterlockedCompareExchange ((volatile long *) atomic, newval,
      oldval) == oldval;
}

static inline gpointer
hx_atomic_pointer_get (void * const volatile * atomic)
{
  gpointer v = (gpointer) *atomic;
  _ReadWriteBarrier ();
  return v;
}

static inline void
hx_atomic_pointer_set (void * volatile * atomic,
                       gpointer newval)
{
  _ReadWriteBarrier ();
  *atomic = newval;
  _ReadWriteBarrier ();
}

static inline gboolean
hx_atomic_pointer_cas (void * volatile * atomic,
                       gpointer oldval,
                       gpointer newval)
{
  return _InterlockedCompareExchangePointer (atomic, newval, oldval) == oldval;
}

# define g_atomic_pointer_get(atomic) \
    hx_atomic_pointer_get ((void * const volatile *) (atomic))
# define g_atomic_pointer_set(atomic, newval) \
    hx_atomic_pointer_set ((void * volatile *) (atomic), (gpointer) (newval))
# define g_atomic_pointer_compare_and_exchange(atomic, oldval, newval) \
    hx_atomic_pointer_cas ((void * volatile *) (atomic), \
        (gpointer) (oldval), (gpointer) (newval))

#endif

G_END_DECLS

#endif
/* ==== inlined header: hxthread.h ==== */
/*
 * hoox nano-glib: threading primitives.
 *
 * GMutex / GRecMutex / GPrivate. Types are defined with opaque, zero-
 * initialisable storage so that statically-declared, implicitly-initialised
 * mutexes (as GLib allows) work without an init race. The native backing is
 * cast inside hxthread.c (Win32 SRWLOCK / FLS; pthread on POSIX).
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __HOOX_COMPAT_THREAD_H__
#define __HOOX_COMPAT_THREAD_H__


G_BEGIN_DECLS

typedef struct _GMutex GMutex;
typedef struct _GRecMutex GRecMutex;
typedef struct _GPrivate GPrivate;
typedef void GThread;

/* Opaque per-thread identity (current OS thread id as a pointer). */
GThread * g_thread_self (void);

#define G_USEC_PER_SEC 1000000
void g_usleep (gulong microseconds);

struct _GMutex
{
  void * p;           /* SRWLOCK (one pointer) / pthread_mutex_t * */
};

struct _GRecMutex
{
  void * srw;         /* SRWLOCK */
  gsize owner;        /* owning thread id (0 = none) */
  guint32 count;      /* recursion depth */
#if GLIB_SIZEOF_VOID_P == 4
  guint32 pad;
#endif
};

struct _GPrivate
{
  void * impl;   /* lazily-allocated native key wrapper (atomic access) */
  GDestroyNotify notify;
};

#define G_PRIVATE_INIT(notify) { NULL, (notify) }

void g_mutex_init (GMutex * mutex);
void g_mutex_clear (GMutex * mutex);
void g_mutex_lock (GMutex * mutex);
gboolean g_mutex_trylock (GMutex * mutex);
void g_mutex_unlock (GMutex * mutex);

void g_rec_mutex_init (GRecMutex * mutex);
void g_rec_mutex_clear (GRecMutex * mutex);
void g_rec_mutex_lock (GRecMutex * mutex);
gboolean g_rec_mutex_trylock (GRecMutex * mutex);
void g_rec_mutex_unlock (GRecMutex * mutex);

gpointer g_private_get (GPrivate * key);
void g_private_set (GPrivate * key, gpointer value);
void g_private_replace (GPrivate * key, gpointer value);

/* one-time initialisation (bracketing enter/leave). Simple global-lock
 * implementation: correct for non-nesting inits (cpu features, etc.). */
gboolean g_once_init_enter_impl (volatile void * location);
void g_once_init_leave_impl (volatile void * location, gsize result);

#define g_once_init_enter(location) \
    (g_atomic_pointer_get ((gsize *) (void *) (location)) == 0 \
        ? g_once_init_enter_impl ((location)) \
        : FALSE)
#define g_once_init_leave(location, result) \
    g_once_init_leave_impl ((location), (gsize) (result))

G_END_DECLS

#endif
/* ==== inlined header: hxarray.h ==== */
/*
 * hoox nano-glib: GArray and GPtrArray.
 *
 * Public struct layout matches GLib (GArray = {data,len}, GPtrArray =
 * {pdata,len}) so g_array_index / g_ptr_array_index and direct field access in
 * extracted gum code keep working.
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __HOOX_COMPAT_ARRAY_H__
#define __HOOX_COMPAT_ARRAY_H__


G_BEGIN_DECLS

typedef struct _GArray GArray;
typedef struct _GPtrArray GPtrArray;

struct _GArray
{
  gchar * data;
  guint len;
};

struct _GPtrArray
{
  gpointer * pdata;
  guint len;
};

/* ---- GArray ------------------------------------------------------------- */

GArray * g_array_new (gboolean zero_terminated, gboolean clear,
    guint element_size);
GArray * g_array_sized_new (gboolean zero_terminated, gboolean clear,
    guint element_size, guint reserved_size);
void g_array_set_clear_func (GArray * array, GDestroyNotify clear_func);
gchar * g_array_free (GArray * array, gboolean free_segment);
GArray * g_array_ref (GArray * array);
void g_array_unref (GArray * array);
guint g_array_get_element_size (GArray * array);

GArray * g_array_append_vals (GArray * array, gconstpointer data, guint len);
GArray * g_array_prepend_vals (GArray * array, gconstpointer data, guint len);
GArray * g_array_insert_vals (GArray * array, guint index_,
    gconstpointer data, guint len);
GArray * g_array_set_size (GArray * array, guint length);
GArray * g_array_remove_index (GArray * array, guint index_);
GArray * g_array_remove_index_fast (GArray * array, guint index_);
GArray * g_array_remove_range (GArray * array, guint index_, guint length);
gpointer g_array_steal (GArray * array, gsize * len);

#define g_array_append_val(a, v) g_array_append_vals ((a), &(v), 1)
#define g_array_prepend_val(a, v) g_array_prepend_vals ((a), &(v), 1)
#define g_array_insert_val(a, i, v) g_array_insert_vals ((a), (i), &(v), 1)
#define g_array_index(a, type, i) (((type *) (void *) (a)->data)[(i)])

/* ---- GPtrArray ---------------------------------------------------------- */

GPtrArray * g_ptr_array_new (void);
GPtrArray * g_ptr_array_sized_new (guint reserved_size);
GPtrArray * g_ptr_array_new_with_free_func (GDestroyNotify element_free_func);
GPtrArray * g_ptr_array_new_full (guint reserved_size,
    GDestroyNotify element_free_func);
void g_ptr_array_set_free_func (GPtrArray * array,
    GDestroyNotify element_free_func);
gpointer * g_ptr_array_free (GPtrArray * array, gboolean free_segment);
GPtrArray * g_ptr_array_ref (GPtrArray * array);
void g_ptr_array_unref (GPtrArray * array);

void g_ptr_array_add (GPtrArray * array, gpointer data);
void g_ptr_array_set_size (GPtrArray * array, gint length);
gboolean g_ptr_array_remove (GPtrArray * array, gpointer data);
gboolean g_ptr_array_remove_fast (GPtrArray * array, gpointer data);
gpointer g_ptr_array_remove_index (GPtrArray * array, guint index_);
gpointer g_ptr_array_remove_index_fast (GPtrArray * array, guint index_);
void g_ptr_array_foreach (GPtrArray * array, GFunc func, gpointer user_data);
void g_ptr_array_sort (GPtrArray * array, GCompareFunc compare_func);
gboolean g_ptr_array_find (GPtrArray * array, gconstpointer needle,
    guint * index_);
gpointer * g_ptr_array_steal (GPtrArray * array, gsize * len);

#define g_ptr_array_index(a, i) ((a)->pdata[(i)])

G_END_DECLS

#endif
/* ==== inlined header: hxhash.h ==== */
/*
 * hoox nano-glib: GHashTable.
 *
 * Separate-chaining hash table with GLib-compatible API, iterator, and the
 * common hash/equal helpers.
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __HOOX_COMPAT_HASH_H__
#define __HOOX_COMPAT_HASH_H__


G_BEGIN_DECLS

typedef struct _GHashTable GHashTable;

typedef struct _GHashTableIter GHashTableIter;

struct _GHashTableIter
{
  gpointer table;
  gssize bucket;
  gpointer node;
  gpointer prev;
  int version;
  int reserved;
};

GHashTable * g_hash_table_new (GHashFunc hash_func, GEqualFunc key_equal_func);
GHashTable * g_hash_table_new_full (GHashFunc hash_func,
    GEqualFunc key_equal_func, GDestroyNotify key_destroy_func,
    GDestroyNotify value_destroy_func);

GHashTable * g_hash_table_ref (GHashTable * hash_table);
void g_hash_table_unref (GHashTable * hash_table);
void g_hash_table_destroy (GHashTable * hash_table);

gboolean g_hash_table_insert (GHashTable * hash_table, gpointer key,
    gpointer value);
gboolean g_hash_table_replace (GHashTable * hash_table, gpointer key,
    gpointer value);
gboolean g_hash_table_add (GHashTable * hash_table, gpointer key);

gpointer g_hash_table_lookup (GHashTable * hash_table, gconstpointer key);
gboolean g_hash_table_lookup_extended (GHashTable * hash_table,
    gconstpointer lookup_key, gpointer * orig_key, gpointer * value);
gboolean g_hash_table_contains (GHashTable * hash_table, gconstpointer key);

gboolean g_hash_table_remove (GHashTable * hash_table, gconstpointer key);
gboolean g_hash_table_steal (GHashTable * hash_table, gconstpointer key);
void g_hash_table_remove_all (GHashTable * hash_table);

void g_hash_table_foreach (GHashTable * hash_table, GHFunc func,
    gpointer user_data);
guint g_hash_table_foreach_remove (GHashTable * hash_table, GHRFunc func,
    gpointer user_data);
gpointer g_hash_table_find (GHashTable * hash_table, GHRFunc predicate,
    gpointer user_data);
guint g_hash_table_size (GHashTable * hash_table);

void g_hash_table_iter_init (GHashTableIter * iter, GHashTable * hash_table);
gboolean g_hash_table_iter_next (GHashTableIter * iter, gpointer * key,
    gpointer * value);
void g_hash_table_iter_remove (GHashTableIter * iter);

/* hash / equal helpers */
guint g_direct_hash (gconstpointer v);
gboolean g_direct_equal (gconstpointer a, gconstpointer b);
guint g_int_hash (gconstpointer v);
gboolean g_int_equal (gconstpointer a, gconstpointer b);
guint g_int64_hash (gconstpointer v);
gboolean g_int64_equal (gconstpointer a, gconstpointer b);
guint g_str_hash (gconstpointer v);
gboolean g_str_equal (gconstpointer a, gconstpointer b);

G_END_DECLS

#endif
/* ==== inlined header: hxlist.h ==== */
/*
 * hoox nano-glib: GSList, GList, GQueue.
 *
 * Public node layout matches GLib so intrusive traversal in extracted gum
 * code (node->data / node->next / node->prev) keeps working.
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __HOOX_COMPAT_LIST_H__
#define __HOOX_COMPAT_LIST_H__


G_BEGIN_DECLS

typedef struct _GSList GSList;
typedef struct _GList GList;
typedef struct _GQueue GQueue;

struct _GSList
{
  gpointer data;
  GSList * next;
};

struct _GList
{
  gpointer data;
  GList * next;
  GList * prev;
};

struct _GQueue
{
  GList * head;
  GList * tail;
  guint length;
};

#define G_QUEUE_INIT { NULL, NULL, 0 }

#define g_slist_next(slist) ((slist) ? (slist)->next : NULL)
#define g_list_next(list) ((list) ? (list)->next : NULL)
#define g_list_previous(list) ((list) ? (list)->prev : NULL)

/* ---- GSList ------------------------------------------------------------- */

GSList * g_slist_append (GSList * list, gpointer data);
GSList * g_slist_prepend (GSList * list, gpointer data);
GSList * g_slist_insert (GSList * list, gpointer data, gint position);
GSList * g_slist_remove (GSList * list, gconstpointer data);
GSList * g_slist_remove_link (GSList * list, GSList * link_);
GSList * g_slist_delete_link (GSList * list, GSList * link_);
GSList * g_slist_find (GSList * list, gconstpointer data);
GSList * g_slist_last (GSList * list);
GSList * g_slist_nth (GSList * list, guint n);
gpointer g_slist_nth_data (GSList * list, guint n);
guint g_slist_length (GSList * list);
GSList * g_slist_reverse (GSList * list);
void g_slist_foreach (GSList * list, GFunc func, gpointer user_data);
void g_slist_free (GSList * list);
void g_slist_free_1 (GSList * list);
void g_slist_free_full (GSList * list, GDestroyNotify free_func);

/* ---- GList -------------------------------------------------------------- */

GList * g_list_append (GList * list, gpointer data);
GList * g_list_prepend (GList * list, gpointer data);
GList * g_list_insert (GList * list, gpointer data, gint position);
GList * g_list_remove (GList * list, gconstpointer data);
GList * g_list_remove_link (GList * list, GList * llink);
GList * g_list_delete_link (GList * list, GList * link_);
GList * g_list_find (GList * list, gconstpointer data);
GList * g_list_first (GList * list);
GList * g_list_last (GList * list);
GList * g_list_nth (GList * list, guint n);
gpointer g_list_nth_data (GList * list, guint n);
guint g_list_length (GList * list);
GList * g_list_reverse (GList * list);
void g_list_foreach (GList * list, GFunc func, gpointer user_data);
void g_list_free (GList * list);
void g_list_free_full (GList * list, GDestroyNotify free_func);

/* ---- GQueue ------------------------------------------------------------- */

GQueue * g_queue_new (void);
void g_queue_init (GQueue * queue);
void g_queue_clear (GQueue * queue);
void g_queue_free (GQueue * queue);
gboolean g_queue_is_empty (GQueue * queue);
guint g_queue_get_length (GQueue * queue);
void g_queue_push_head (GQueue * queue, gpointer data);
void g_queue_push_tail (GQueue * queue, gpointer data);
gpointer g_queue_pop_head (GQueue * queue);
gpointer g_queue_pop_tail (GQueue * queue);
gpointer g_queue_peek_head (GQueue * queue);
gpointer g_queue_peek_tail (GQueue * queue);
void g_queue_foreach (GQueue * queue, GFunc func, gpointer user_data);
gboolean g_queue_remove (GQueue * queue, gconstpointer data);

G_END_DECLS

#endif
/* ==== inlined header: hxstring.h ==== */
/*
 * hoox nano-glib: GString.
 *
 * Growable string buffer, mainly used by the tests and target functions.
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __HOOX_COMPAT_STRING_H__
#define __HOOX_COMPAT_STRING_H__


#include <stdarg.h>

G_BEGIN_DECLS

typedef struct _GString GString;

struct _GString
{
  gchar * str;
  gsize len;
  gsize allocated_len;
};

GString * g_string_new (const gchar * init);
GString * g_string_sized_new (gsize dfl_size);
gchar * g_string_free (GString * string, gboolean free_segment);

GString * g_string_assign (GString * string, const gchar * rval);
GString * g_string_truncate (GString * string, gsize len);
GString * g_string_append (GString * string, const gchar * val);
GString * g_string_append_c (GString * string, gchar c);
GString * g_string_append_len (GString * string, const gchar * val,
    gssize len);
GString * g_string_prepend (GString * string, const gchar * val);
GString * g_string_append_printf (GString * string, const gchar * format, ...)
    G_GNUC_PRINTF (2, 3);
GString * g_string_append_vprintf (GString * string, const gchar * format,
    va_list args);

G_END_DECLS

#endif
/* ==== inlined header: hxstrfuncs.h ==== */
/*
 * hoox nano-glib: string utility functions.
 *
 * g_strdup family and the string predicates used by extracted gum code.
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __HOOX_COMPAT_STRFUNCS_H__
#define __HOOX_COMPAT_STRFUNCS_H__


#include <stdarg.h>

G_BEGIN_DECLS

gchar * g_strdup (const gchar * str);
gchar * g_strndup (const gchar * str, gsize n);
gchar * g_strdup_printf (const gchar * format, ...) G_GNUC_PRINTF (1, 2);
gchar * g_strdup_vprintf (const gchar * format, va_list args);
gchar * g_strconcat (const gchar * string1, ...) G_GNUC_NULL_TERMINATED;

gint g_strcmp0 (const gchar * str1, const gchar * str2);
gboolean g_str_has_prefix (const gchar * str, const gchar * prefix);
gboolean g_str_has_suffix (const gchar * str, const gchar * suffix);

gsize g_strlcpy (gchar * dest, const gchar * src, gsize dest_size);
gsize g_strlcat (gchar * dest, const gchar * src, gsize dest_size);

#include <stdio.h>
#define g_snprintf(str, n, ...) ((void) snprintf ((str), (n), __VA_ARGS__))

G_END_DECLS

#endif

#endif

#if CS_API_MAJOR >= 6
# define CS_ARCH_ARM64 CS_ARCH_AARCH64
#endif

#if !defined (GUM_STATIC) && defined (G_OS_WIN32)
#  ifdef GUM_EXPORTS
#    define GUM_API __declspec(dllexport)
#  else
#    define GUM_API __declspec(dllimport)
#  endif
#else
#  define GUM_API
#endif

G_BEGIN_DECLS

#define GUM_ERROR gum_error_quark ()

typedef enum {
  GUM_ERROR_FAILED,
  GUM_ERROR_NOT_FOUND,
  GUM_ERROR_EXISTS,
  GUM_ERROR_PERMISSION_DENIED,
  GUM_ERROR_INVALID_ARGUMENT,
  GUM_ERROR_NOT_SUPPORTED,
  GUM_ERROR_INVALID_DATA,
} GumError;

typedef guint64 GumAddress;
#define GUM_ADDRESS(a) ((GumAddress) (guintptr) (a))
#define GUM_TYPE_ADDRESS (gum_address_get_type ())
typedef guint GumOS;
typedef guint GumCallingConvention;
typedef guint GumAbiType;
typedef guint GumCpuFeatures;
typedef guint GumInstructionEncoding;
typedef guint GumArgType;
typedef struct _GumArgument GumArgument;
typedef guint GumBranchHint;
typedef struct _GumIA32CpuContext GumIA32CpuContext;
typedef struct _GumX64CpuContext GumX64CpuContext;
typedef struct _GumArmCpuContext GumArmCpuContext;
typedef union _GumArmVectorReg GumArmVectorReg;
typedef struct _GumArm64CpuContext GumArm64CpuContext;
typedef union _GumArm64VectorReg GumArm64VectorReg;
typedef struct _GumMipsCpuContext GumMipsCpuContext;
typedef guint GumRelocationScenario;

#if defined (_M_IX86) || defined (__i386__)
# define GUM_NATIVE_CPU GUM_CPU_IA32
# define GUM_DEFAULT_CS_ARCH CS_ARCH_X86
# define gum_cs_arch_register_native cs_arch_register_x86
/**
 * GUM_DEFAULT_CS_MODE: (skip)
 */
# define GUM_DEFAULT_CS_MODE CS_MODE_32
typedef GumIA32CpuContext GumCpuContext;
#elif defined (_M_X64) || defined (__x86_64__)
# define GUM_NATIVE_CPU GUM_CPU_AMD64
# define GUM_DEFAULT_CS_ARCH CS_ARCH_X86
# define gum_cs_arch_register_native cs_arch_register_x86
/**
 * GUM_DEFAULT_CS_MODE: (skip)
 */
# define GUM_DEFAULT_CS_MODE CS_MODE_64
typedef GumX64CpuContext GumCpuContext;
#elif defined (_M_ARM) || defined (__arm__)
# define GUM_NATIVE_CPU GUM_CPU_ARM
# define GUM_DEFAULT_CS_ARCH CS_ARCH_ARM
# define gum_cs_arch_register_native cs_arch_register_arm
/**
 * GUM_DEFAULT_CS_MODE: (skip)
 */
# define GUM_DEFAULT_CS_MODE \
    ((cs_mode) (CS_MODE_ARM | CS_MODE_V8 | GUM_DEFAULT_CS_ENDIAN))
# define GUM_PSR_T_BIT 0x20
typedef GumArmCpuContext GumCpuContext;
#elif defined (_M_ARM64) || defined (__aarch64__)
# define GUM_NATIVE_CPU GUM_CPU_ARM64
# define GUM_DEFAULT_CS_ARCH CS_ARCH_ARM64
# define gum_cs_arch_register_native cs_arch_register_arm64
/**
 * GUM_DEFAULT_CS_MODE: (skip)
 */
# define GUM_DEFAULT_CS_MODE GUM_DEFAULT_CS_ENDIAN
typedef GumArm64CpuContext GumCpuContext;
#elif defined (__mips__)
# define GUM_NATIVE_CPU GUM_CPU_MIPS
# define GUM_DEFAULT_CS_ARCH CS_ARCH_MIPS
# define gum_cs_arch_register_native cs_arch_register_mips
# if GLIB_SIZEOF_VOID_P == 4
/**
 * GUM_DEFAULT_CS_MODE: (skip)
 */
#  define GUM_DEFAULT_CS_MODE ((cs_mode) \
    (CS_MODE_MIPS32 | GUM_DEFAULT_CS_ENDIAN))
# else
/**
 * GUM_DEFAULT_CS_MODE: (skip)
 */
#  define GUM_DEFAULT_CS_MODE ((cs_mode) \
    (CS_MODE_MIPS64 | GUM_DEFAULT_CS_ENDIAN))
# endif
typedef GumMipsCpuContext GumCpuContext;
#else
# error Unsupported architecture.
#endif
/*
 * The only non-legacy big-endian configuration on 32-bit ARM systems is BE8.
 * In this configuration, whilst the data is in big-endian, the code stream is
 * still in little-endian. Since Capstone is disassembling the code stream, it
 * should work in little-endian even on BE8 systems. On big-endian 64-bit ARM
 * systems, the code stream is likewise in little-endian.
 */
#if G_BYTE_ORDER == G_LITTLE_ENDIAN || \
    defined (__arm__) || \
    defined (_M_ARM64) || \
    defined (__aarch64__)
# define GUM_DEFAULT_CS_ENDIAN CS_MODE_LITTLE_ENDIAN
#else
# define GUM_DEFAULT_CS_ENDIAN CS_MODE_BIG_ENDIAN
#endif
#ifdef G_OS_WIN32
# define GUM_NATIVE_ABI            GUM_ABI_WINDOWS
# define GUM_NATIVE_ABI_IS_WINDOWS 1
# define GUM_NATIVE_ABI_IS_UNIX    0
#else
# define GUM_NATIVE_ABI            GUM_ABI_UNIX
# define GUM_NATIVE_ABI_IS_WINDOWS 0
# define GUM_NATIVE_ABI_IS_UNIX    1
#endif

enum _GumOS
{
  GUM_OS_NONE,
  GUM_OS_WINDOWS,
  GUM_OS_MACOS,
  GUM_OS_LINUX,
  GUM_OS_IOS,
  GUM_OS_WATCHOS,
  GUM_OS_TVOS,
  GUM_OS_XROS,
  GUM_OS_ANDROID,
  GUM_OS_FREEBSD,
  GUM_OS_QNX
};

enum _GumCallingConvention
{
  GUM_CALL_CAPI,
  GUM_CALL_SYSAPI
};

enum _GumAbiType
{
  GUM_ABI_UNIX,
  GUM_ABI_WINDOWS
};

typedef enum {
  GUM_CPU_INVALID,
  GUM_CPU_IA32,
  GUM_CPU_AMD64,
  GUM_CPU_ARM,
  GUM_CPU_ARM64,
  GUM_CPU_MIPS
} GumCpuType;

enum _GumCpuFeatures
{
  GUM_CPU_AVX2            = 1 << 0,
  GUM_CPU_CET_SS          = 1 << 1,
  GUM_CPU_THUMB_INTERWORK = 1 << 2,
  GUM_CPU_VFP2            = 1 << 3,
  GUM_CPU_VFP3            = 1 << 4,
  GUM_CPU_VFPD32          = 1 << 5,
  GUM_CPU_PTRAUTH         = 1 << 6,
};

typedef enum {
  GUM_MEMORY_ACCESS_OPEN,
  GUM_MEMORY_ACCESS_EXCLUSIVE,
} GumMemoryAccess;

enum _GumInstructionEncoding
{
  GUM_INSTRUCTION_DEFAULT,
  GUM_INSTRUCTION_SPECIAL
};

enum _GumArgType
{
  GUM_ARG_ADDRESS,
  GUM_ARG_REGISTER
};

struct _GumArgument
{
  GumArgType type;

  union
  {
    GumAddress address;
    gint reg;
  } value;
};

enum _GumBranchHint
{
  GUM_NO_HINT,
  GUM_LIKELY,
  GUM_UNLIKELY
};

struct _GumIA32CpuContext
{
  guint32 eip;

  guint32 edi;
  guint32 esi;
  guint32 ebp;
  guint32 esp;
  guint32 ebx;
  guint32 edx;
  guint32 ecx;
  guint32 eax;
};

struct _GumX64CpuContext
{
  guint64 rip;

  guint64 r15;
  guint64 r14;
  guint64 r13;
  guint64 r12;
  guint64 r11;
  guint64 r10;
  guint64 r9;
  guint64 r8;

  guint64 rdi;
  guint64 rsi;
  guint64 rbp;
  guint64 rsp;
  guint64 rbx;
  guint64 rdx;
  guint64 rcx;
  guint64 rax;
};

union _GumArmVectorReg
{
  guint8 q[16];
  gdouble d[2];
  gfloat s[4];
};

struct _GumArmCpuContext
{
  guint32 pc;
  guint32 sp;
  guint32 cpsr;

  guint32 r8;
  guint32 r9;
  guint32 r10;
  guint32 r11;
  guint32 r12;

  GumArmVectorReg v[16];

  guint32 _padding;

  guint32 r[8];
  guint32 lr;
};

union _GumArm64VectorReg
{
  guint8 q[16];
  gdouble d;
  gfloat s;
  guint16 h;
  guint8 b;
};

struct _GumArm64CpuContext
{
  guint64 pc;
  guint64 sp;
  guint64 nzcv;

  guint64 x[29];
  guint64 fp;
  guint64 lr;

#ifndef G_OS_NONE
  /* Bare-metal threads can be entered with a near-exhausted kernel stack, so
   * there the trampolines stay integer-only and skip the vector registers. */
  GumArm64VectorReg v[32];
#endif
};

struct _GumMipsCpuContext
{
  /*
   * This structure represents the register state pushed onto the stack by the
   * trampoline which allows us to vector from the original minimal assembly
   * hook to architecture agnostic C code inside frida-gum. These registers are
   * natively sized. Even if some have not been expanded to 64-bits from the
   * MIPS32 architecture MIPS can only perform aligned data access and as such
   * pushing zero extended values is simpler than attempting to push minimally
   * sized data types.
   */
  gsize pc;

  gsize gp;
  gsize sp;
  gsize fp;
  gsize ra;

  gsize hi;
  gsize lo;

  gsize at;

  gsize v0;
  gsize v1;

  gsize a0;
  gsize a1;
  gsize a2;
  gsize a3;

  gsize t0;
  gsize t1;
  gsize t2;
  gsize t3;
  gsize t4;
  gsize t5;
  gsize t6;
  gsize t7;
  gsize t8;
  gsize t9;

  gsize s0;
  gsize s1;
  gsize s2;
  gsize s3;
  gsize s4;
  gsize s5;
  gsize s6;
  gsize s7;

  gsize k0;
  gsize k1;
};

enum _GumRelocationScenario
{
  GUM_SCENARIO_OFFLINE,
  GUM_SCENARIO_ONLINE
};

typedef enum {
  GUM_RELOCATION_DEFAULT,
  GUM_RELOCATION_CHECKED,
  GUM_RELOCATION_UNCHECKED,
  GUM_RELOCATION_FORCED,
} GumRelocationPolicy;

#ifndef __arm__
# if GLIB_SIZEOF_VOID_P == 8
#  define GUM_CPU_CONTEXT_XAX(c) ((c)->rax)
#  define GUM_CPU_CONTEXT_XCX(c) ((c)->rcx)
#  define GUM_CPU_CONTEXT_XDX(c) ((c)->rdx)
#  define GUM_CPU_CONTEXT_XBX(c) ((c)->rbx)
#  define GUM_CPU_CONTEXT_XSP(c) ((c)->rsp)
#  define GUM_CPU_CONTEXT_XBP(c) ((c)->rbp)
#  define GUM_CPU_CONTEXT_XSI(c) ((c)->rsi)
#  define GUM_CPU_CONTEXT_XDI(c) ((c)->rdi)
#  define GUM_CPU_CONTEXT_XIP(c) ((c)->rip)
#  define GUM_CPU_CONTEXT_OFFSET_XAX (G_STRUCT_OFFSET (GumCpuContext, rax))
#  define GUM_CPU_CONTEXT_OFFSET_XCX (G_STRUCT_OFFSET (GumCpuContext, rcx))
#  define GUM_CPU_CONTEXT_OFFSET_XDX (G_STRUCT_OFFSET (GumCpuContext, rdx))
#  define GUM_CPU_CONTEXT_OFFSET_XBX (G_STRUCT_OFFSET (GumCpuContext, rbx))
#  define GUM_CPU_CONTEXT_OFFSET_XSP (G_STRUCT_OFFSET (GumCpuContext, rsp))
#  define GUM_CPU_CONTEXT_OFFSET_XBP (G_STRUCT_OFFSET (GumCpuContext, rbp))
#  define GUM_CPU_CONTEXT_OFFSET_XSI (G_STRUCT_OFFSET (GumCpuContext, rsi))
#  define GUM_CPU_CONTEXT_OFFSET_XDI (G_STRUCT_OFFSET (GumCpuContext, rdi))
#  define GUM_CPU_CONTEXT_OFFSET_XIP (G_STRUCT_OFFSET (GumCpuContext, rip))
# else
#  define GUM_CPU_CONTEXT_XAX(c) ((c)->eax)
#  define GUM_CPU_CONTEXT_XCX(c) ((c)->ecx)
#  define GUM_CPU_CONTEXT_XDX(c) ((c)->edx)
#  define GUM_CPU_CONTEXT_XBX(c) ((c)->ebx)
#  define GUM_CPU_CONTEXT_XSP(c) ((c)->esp)
#  define GUM_CPU_CONTEXT_XBP(c) ((c)->ebp)
#  define GUM_CPU_CONTEXT_XSI(c) ((c)->esi)
#  define GUM_CPU_CONTEXT_XDI(c) ((c)->edi)
#  define GUM_CPU_CONTEXT_XIP(c) ((c)->eip)
#  define GUM_CPU_CONTEXT_OFFSET_XAX (G_STRUCT_OFFSET (GumCpuContext, eax))
#  define GUM_CPU_CONTEXT_OFFSET_XCX (G_STRUCT_OFFSET (GumCpuContext, ecx))
#  define GUM_CPU_CONTEXT_OFFSET_XDX (G_STRUCT_OFFSET (GumCpuContext, edx))
#  define GUM_CPU_CONTEXT_OFFSET_XBX (G_STRUCT_OFFSET (GumCpuContext, ebx))
#  define GUM_CPU_CONTEXT_OFFSET_XSP (G_STRUCT_OFFSET (GumCpuContext, esp))
#  define GUM_CPU_CONTEXT_OFFSET_XBP (G_STRUCT_OFFSET (GumCpuContext, ebp))
#  define GUM_CPU_CONTEXT_OFFSET_XSI (G_STRUCT_OFFSET (GumCpuContext, esi))
#  define GUM_CPU_CONTEXT_OFFSET_XDI (G_STRUCT_OFFSET (GumCpuContext, edi))
#  define GUM_CPU_CONTEXT_OFFSET_XIP (G_STRUCT_OFFSET (GumCpuContext, eip))
# endif
#endif

#define GUM_MAX_PATH                 260
#define GUM_MAX_TYPE_NAME             16
#define GUM_MAX_SYMBOL_NAME         2048

#define GUM_MAX_THREADS              768
#define GUM_MAX_CALL_DEPTH            32
#define GUM_MAX_BACKTRACE_DEPTH       16
#define GUM_MAX_WORST_CASE_INFO_SIZE 128

#define GUM_MAX_LISTENERS_PER_FUNCTION 2
#define GUM_MAX_LISTENER_DATA       1024

#define GUM_MAX_THREAD_RANGES 2

#if defined (HAVE_I386)
# if GLIB_SIZEOF_VOID_P == 8
#  define GUM_CPU_MODE CS_MODE_64
#  define GUM_X86_THUNK
# else
#  define GUM_CPU_MODE CS_MODE_32
#  define GUM_X86_THUNK GUM_FASTCALL
# endif
#else
# if G_BYTE_ORDER == G_LITTLE_ENDIAN
#  define GUM_CPU_MODE CS_MODE_LITTLE_ENDIAN
# else
#  define GUM_CPU_MODE CS_MODE_BIG_ENDIAN
# endif
#endif
#if !defined (G_OS_WIN32) && GLIB_SIZEOF_VOID_P == 8
# define GUM_X86_THUNK_REG_ARG0 GUM_X86_XDI
# define GUM_X86_THUNK_REG_ARG1 GUM_X86_XSI
#else
# define GUM_X86_THUNK_REG_ARG0 GUM_X86_XCX
# define GUM_X86_THUNK_REG_ARG1 GUM_X86_XDX
#endif
#define GUM_RED_ZONE_SIZE 128

#if defined (_M_IX86) || defined (__i386__)
# ifdef _MSC_VER
#  define GUM_CDECL __cdecl
#  define GUM_STDCALL __stdcall
#  define GUM_FASTCALL __fastcall
# else
#  define GUM_CDECL __attribute__ ((cdecl))
#  define GUM_STDCALL __attribute__ ((stdcall))
#  define GUM_FASTCALL __attribute__ ((fastcall))
# endif
#else
# define GUM_CDECL
# define GUM_STDCALL
# define GUM_FASTCALL
#endif

#ifdef _MSC_VER
# define GUM_NOINLINE __declspec (noinline)
#else
# define GUM_NOINLINE __attribute__ ((noinline))
#endif

#define GUM_ALIGN_POINTER(t, p, b) \
    ((t) GSIZE_TO_POINTER (((GPOINTER_TO_SIZE (p) + ((gsize) (b - 1))) & \
        ~((gsize) (b - 1)))))
#define GUM_ALIGN_SIZE(s, b) \
    ((((gsize) s) + ((gsize) (b - 1))) & ~((gsize) (b - 1)))

#define GUM_FUNCPTR_TO_POINTER(f) (GSIZE_TO_POINTER (f))
#define GUM_POINTER_TO_FUNCPTR(t, p) ((t) GPOINTER_TO_SIZE (p))

#define GUM_INT2_MASK  0x00000003U
#define GUM_INT3_MASK  0x00000007U
#define GUM_INT4_MASK  0x0000000fU
#define GUM_INT5_MASK  0x0000001fU
#define GUM_INT6_MASK  0x0000003fU
#define GUM_INT8_MASK  0x000000ffU
#define GUM_INT10_MASK 0x000003ffU
#define GUM_INT11_MASK 0x000007ffU
#define GUM_INT12_MASK 0x00000fffU
#define GUM_INT14_MASK 0x00003fffU
#define GUM_INT16_MASK 0x0000ffffU
#define GUM_INT18_MASK 0x0003ffffU
#define GUM_INT19_MASK 0x0007ffffU
#define GUM_INT24_MASK 0x00ffffffU
#define GUM_INT26_MASK 0x03ffffffU
#define GUM_INT28_MASK 0x0fffffffU
#define GUM_INT32_MASK 0xffffffffU

#define GUM_IS_WITHIN_UINT7_RANGE(i) \
    (((gint64) (i)) >= G_GINT64_CONSTANT (0) && \
     ((gint64) (i)) <= G_GINT64_CONSTANT (127))
#define GUM_IS_WITHIN_UINT8_RANGE(i) \
    (((gint64) (i)) >= G_GINT64_CONSTANT (0) && \
     ((gint64) (i)) <= G_GINT64_CONSTANT (255))
#define GUM_IS_WITHIN_INT8_RANGE(i) \
    (((gint64) (i)) >= G_GINT64_CONSTANT (-128) && \
     ((gint64) (i)) <= G_GINT64_CONSTANT (127))
#define GUM_IS_WITHIN_INT11_RANGE(i) \
    (((gint64) (i)) >= G_GINT64_CONSTANT (-1024) && \
     ((gint64) (i)) <= G_GINT64_CONSTANT (1023))
#define GUM_IS_WITHIN_INT14_RANGE(i) \
    (((gint64) (i)) >= G_GINT64_CONSTANT (-8192) && \
     ((gint64) (i)) <= G_GINT64_CONSTANT (8191))
#define GUM_IS_WITHIN_INT16_RANGE(i) \
    (((gint64) (i)) >= G_GINT64_CONSTANT (-32768) && \
     ((gint64) (i)) <= G_GINT64_CONSTANT (32767))
#define GUM_IS_WITHIN_INT18_RANGE(i) \
    (((gint64) (i)) >= G_GINT64_CONSTANT (-131072) && \
     ((gint64) (i)) <= G_GINT64_CONSTANT (131071))
#define GUM_IS_WITHIN_INT19_RANGE(i) \
    (((gint64) (i)) >= G_GINT64_CONSTANT (-262144) && \
     ((gint64) (i)) <= G_GINT64_CONSTANT (262143))
#define GUM_IS_WITHIN_INT20_RANGE(i) \
    (((gint64) (i)) >= G_GINT64_CONSTANT (-524288) && \
     ((gint64) (i)) <= G_GINT64_CONSTANT (524287))
#define GUM_IS_WITHIN_INT21_RANGE(i) \
    (((gint64) (i)) >= G_GINT64_CONSTANT (-1048576) && \
     ((gint64) (i)) <= G_GINT64_CONSTANT (1048575))
#define GUM_IS_WITHIN_INT24_RANGE(i) \
    (((gint64) (i)) >= G_GINT64_CONSTANT (-8388608) && \
     ((gint64) (i)) <= G_GINT64_CONSTANT (8388607))
#define GUM_IS_WITHIN_INT26_RANGE(i) \
    (((gint64) (i)) >= G_GINT64_CONSTANT (-33554432) && \
     ((gint64) (i)) <= G_GINT64_CONSTANT (33554431))
#define GUM_IS_WITHIN_INT28_RANGE(i) \
    (((gint64) (i)) >= G_GINT64_CONSTANT (-134217728) && \
     ((gint64) (i)) <= G_GINT64_CONSTANT (134217727))
#define GUM_IS_WITHIN_INT32_RANGE(i) \
    (((gint64) (i)) >= (gint64) G_MININT32 && \
     ((gint64) (i)) <= (gint64) G_MAXINT32)

#ifdef G_NORETURN
# define GUM_NORETURN G_NORETURN
#else
# define GUM_NORETURN
#endif

GUM_API GQuark gum_error_quark (void);

GUM_API GUM_NORETURN void gum_panic (const gchar * format, ...)
    G_ANALYZER_NORETURN;

GUM_API GumCpuFeatures gum_query_cpu_features (void);

GUM_API gpointer gum_cpu_context_get_nth_argument (GumCpuContext * self,
    guint n);
GUM_API void gum_cpu_context_replace_nth_argument (GumCpuContext * self,
    guint n, gpointer value);
GUM_API gpointer gum_cpu_context_get_return_value (GumCpuContext * self);
GUM_API void gum_cpu_context_replace_return_value (GumCpuContext * self,
    gpointer value);

GUM_API GType gum_address_get_type (void) G_GNUC_CONST;

G_END_DECLS

#endif
/* ==== inlined header: gummemory.h ==== */
/*
 * Copyright (C) 2008-2026 Ole André Vadla Ravnås <oleavr@nowsecure.com>
 * Copyright (C) 2008 Christian Berentsen <jc.berentsen@gmail.com>
 * Copyright (C) 2025 Francesco Tamagni <mrmacete@protonmail.ch>
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __GUM_MEMORY_H__
#define __GUM_MEMORY_H__


#define GUM_TYPE_MATCH_PATTERN (gum_match_pattern_get_type ())
#define GUM_TYPE_MEMORY_RANGE (gum_memory_range_get_type ())
#define GUM_MEMORY_RANGE_INCLUDES(r, a) ((a) >= (r)->base_address && \
    (a) < ((r)->base_address + (r)->size))

#define GUM_PAGE_RW ((GumPageProtection) (GUM_PAGE_READ | GUM_PAGE_WRITE))
#define GUM_PAGE_RX ((GumPageProtection) (GUM_PAGE_READ | GUM_PAGE_EXECUTE))
#define GUM_PAGE_RWX ((GumPageProtection) (GUM_PAGE_READ | GUM_PAGE_WRITE | \
    GUM_PAGE_EXECUTE))

G_BEGIN_DECLS

typedef guint GumPtrauthSupport;
typedef guint GumRwxSupport;
typedef guint GumMemoryOperation;
typedef guint GumPageProtection;
typedef struct _GumAddressSpec GumAddressSpec;
typedef struct _GumRangeDetails GumRangeDetails;
typedef struct _GumMemoryRange GumMemoryRange;
typedef struct _GumFileMapping GumFileMapping;
typedef struct _GumMatchPattern GumMatchPattern;
typedef struct _GumPointerMatch GumPointerMatch;

typedef gboolean (* GumMemoryIsNearFunc) (gpointer memory, gpointer address);

enum _GumPtrauthSupport
{
  GUM_PTRAUTH_INVALID,
  GUM_PTRAUTH_UNSUPPORTED,
  GUM_PTRAUTH_SUPPORTED
};

enum _GumRwxSupport
{
  GUM_RWX_NONE,
  GUM_RWX_ALLOCATIONS_ONLY,
  GUM_RWX_FULL
};

enum _GumMemoryOperation
{
  GUM_MEMOP_INVALID,
  GUM_MEMOP_READ,
  GUM_MEMOP_WRITE,
  GUM_MEMOP_EXECUTE
};

enum _GumPageProtection
{
  GUM_PAGE_NO_ACCESS = 0,
  GUM_PAGE_READ      = (1 << 0),
  GUM_PAGE_WRITE     = (1 << 1),
  GUM_PAGE_EXECUTE   = (1 << 2),
};

struct _GumAddressSpec
{
  gpointer near_address;
  gsize max_distance;
};

struct _GumRangeDetails
{
  const GumMemoryRange * range;
  GumPageProtection protection;
  const GumFileMapping * file;
};

struct _GumMemoryRange
{
  GumAddress base_address;
  gsize size;
};

struct _GumFileMapping
{
  const gchar * path;
  guint64 offset;
  gsize size;
};

struct _GumPointerMatch
{
  GumAddress address;
  gsize value;
};

typedef gboolean (* GumFoundRangeFunc) (const GumRangeDetails * details,
    gpointer user_data);
typedef void (* GumMemoryPatchApplyFunc) (gpointer mem, gpointer user_data);
typedef void (* GumMemoryPatchPagesApplyFunc) (gpointer mem,
    gpointer target_page, guint n_pages, gpointer user_data);
typedef gboolean (* GumMemoryScanMatchFunc) (GumAddress address, gsize size,
    gpointer user_data);

GUM_API void gum_internal_heap_ref (void);
GUM_API void gum_internal_heap_unref (void);

GUM_API gpointer gum_sign_code_pointer (gpointer value);
GUM_API gpointer gum_strip_code_pointer (gpointer value);
GUM_API GumAddress gum_sign_code_address (GumAddress value);
GUM_API GumAddress gum_strip_code_address (GumAddress value);
GUM_API GumPtrauthSupport gum_query_ptrauth_support (void);
GUM_API guint gum_query_page_size (void);
GUM_API gboolean gum_query_is_rwx_supported (void);
GUM_API GumRwxSupport gum_query_rwx_support (void);
GUM_API gboolean gum_memory_is_readable (gconstpointer address, gsize len);
GUM_API gboolean gum_memory_query_protection (gconstpointer address,
    GumPageProtection * prot);
GUM_API guint8 * gum_memory_read (gconstpointer address, gsize len,
    gsize * n_bytes_read);
GUM_API gboolean gum_memory_write (gpointer address, const guint8 * bytes,
    gsize len);
GUM_API gboolean gum_memory_patch_code (gpointer address, gsize size,
    GumMemoryPatchApplyFunc apply, gpointer apply_data);
GUM_API gboolean gum_memory_patch_code_pages (GPtrArray * sorted_addresses,
    gboolean coalesce, GumMemoryPatchPagesApplyFunc apply,
    gpointer apply_data);
GUM_API gboolean gum_memory_can_remap_writable (void);
GUM_API gpointer gum_memory_try_remap_writable_pages (gpointer first_page,
    guint n_pages);
GUM_API void gum_memory_dispose_writable_pages (gpointer first_page,
    guint n_pages);
GUM_API gboolean gum_memory_mark_code (gpointer address, gsize size);

GUM_API void gum_memory_scan (const GumMemoryRange * range,
    const GumMatchPattern * pattern, GumMemoryScanMatchFunc func,
    gpointer user_data);
GUM_API GArray * gum_memory_find_pointers (const GumMemoryRange * ranges,
    guint n_ranges, const gsize * values, guint n_values, gsize mask);

GUM_API GType gum_match_pattern_get_type (void) G_GNUC_CONST;
GUM_API GumMatchPattern * gum_match_pattern_new_from_string (
    const gchar * pattern_str);
GUM_API GumMatchPattern * gum_match_pattern_ref (GumMatchPattern * pattern);
GUM_API void gum_match_pattern_unref (GumMatchPattern * pattern);
GUM_API guint gum_match_pattern_get_size (const GumMatchPattern * pattern);
GUM_API GPtrArray * gum_match_pattern_get_tokens (
    const GumMatchPattern * pattern);

GUM_API void gum_ensure_code_readable (gconstpointer address, gsize size);

GUM_API void gum_mprotect (gpointer address, gsize size,
    GumPageProtection prot);
GUM_API gboolean gum_try_mprotect (gpointer address, gsize size,
    GumPageProtection prot);

GUM_API void gum_clear_cache (gpointer address, gsize size);

#define gum_new(struct_type, n_structs) \
    ((struct_type *) gum_malloc (n_structs * sizeof (struct_type)))
#define gum_new0(struct_type, n_structs) \
    ((struct_type *) gum_malloc0 (n_structs * sizeof (struct_type)))

GUM_API guint gum_peek_private_memory_usage (void);

GUM_API gpointer gum_malloc (gsize size);
GUM_API gpointer gum_malloc0 (gsize size);
GUM_API gsize gum_malloc_usable_size (gconstpointer mem);
GUM_API gpointer gum_calloc (gsize count, gsize size);
GUM_API gpointer gum_realloc (gpointer mem, gsize size);
GUM_API gpointer gum_memalign (gsize alignment, gsize size);
GUM_API gpointer gum_memdup (gconstpointer mem, gsize byte_size);
GUM_API void gum_free (gpointer mem);

GUM_API gpointer gum_alloc_n_pages (guint n_pages, GumPageProtection prot);
GUM_API gpointer gum_try_alloc_n_pages (guint n_pages, GumPageProtection prot);
GUM_API gpointer gum_alloc_n_pages_near (guint n_pages, GumPageProtection prot,
    const GumAddressSpec * spec);
GUM_API gpointer gum_try_alloc_n_pages_near (guint n_pages,
    GumPageProtection prot, const GumAddressSpec * spec);
GUM_API void gum_query_page_allocation_range (gconstpointer mem, guint size,
    GumMemoryRange * range);
GUM_API void gum_free_pages (gpointer mem);

GUM_API gpointer gum_memory_allocate (gpointer address, gsize size,
    gsize alignment, GumPageProtection prot);
GUM_API gpointer gum_memory_allocate_near (const GumAddressSpec * spec,
    gsize size, gsize alignment, GumPageProtection prot);
GUM_API gboolean gum_memory_free (gpointer address, gsize size);
GUM_API gboolean gum_memory_release (gpointer address, gsize size);
GUM_API gboolean gum_memory_recommit (gpointer address, gsize size,
    GumPageProtection prot);
GUM_API gboolean gum_memory_discard (gpointer address, gsize size);
GUM_API gboolean gum_memory_decommit (gpointer address, gsize size);

GUM_API gboolean gum_address_spec_is_satisfied_by (const GumAddressSpec * spec,
    gconstpointer address);

GUM_API GType gum_memory_range_get_type (void) G_GNUC_CONST;
GUM_API GumMemoryRange * gum_memory_range_copy (const GumMemoryRange * range);
GUM_API void gum_memory_range_free (GumMemoryRange * range);

G_END_DECLS

#endif
/* ==== inlined header: guminterceptor.h ==== */
/*
 * Copyright (C) 2008-2026 Ole André Vadla Ravnås <oleavr@nowsecure.com>
 * Copyright (C) 2008 Christian Berentsen <jc.berentsen@gmail.com>
 * Copyright (C) 2024 Francesco Tamagni <mrmacete@protonmail.ch>
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __GUM_INTERCEPTOR_H__
#define __GUM_INTERCEPTOR_H__

/* ==== inlined header: guminvocationlistener.h ==== */
/*
 * Copyright (C) 2008-2022 Ole André Vadla Ravnås <oleavr@nowsecure.com>
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __GUM_INVOCATION_LISTENER_H__
#define __GUM_INVOCATION_LISTENER_H__

/* ==== inlined header: guminvocationcontext.h ==== */
/*
 * Copyright (C) 2008-2022 Ole André Vadla Ravnås <oleavr@nowsecure.com>
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __GUM_INVOCATION_CONTEXT_H__
#define __GUM_INVOCATION_CONTEXT_H__

/* ==== inlined header: gumprocess.h ==== */
/*
 * Copyright (C) 2008-2026 Ole André Vadla Ravnås <oleavr@nowsecure.com>
 * Copyright (C) 2020-2024 Francesco Tamagni <mrmacete@protonmail.ch>
 * Copyright (C) 2023 Grant Douglas <me@hexplo.it>
 * Copyright (C) 2024 Håvard Sørbø <havard@hsorbo.no>
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __GUM_PROCESS_H__
#define __GUM_PROCESS_H__

/* ==== inlined header: gummodule.h ==== */
/*
 * hoox — minimal GumModule shim.
 *
 * frida-gum's GumModule is a GObject interface exposing rich module
 * introspection. hoox needs only a tiny module/range abstraction: gumprocess.h
 * references the GumModule type, and the tests query the main module's range.
 * The full introspection API (imports/exports/symbols/sections) is dropped.
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __GUM_MODULE_H__
#define __GUM_MODULE_H__


G_BEGIN_DECLS

typedef struct _GumModule GumModule;

GUM_API const gchar * gum_module_get_name (GumModule * self);
GUM_API const gchar * gum_module_get_path (GumModule * self);
GUM_API const GumMemoryRange * gum_module_get_range (GumModule * self);
GUM_API GumAddress gum_module_find_export_by_name (GumModule * self,
    const gchar * symbol_name);

G_END_DECLS

#endif

#define GUM_THREAD_ID_INVALID ((GumThreadId) -1)
#define GUM_TYPE_THREAD_DETAILS (gum_thread_details_get_type ())

G_BEGIN_DECLS

typedef guint GumProcessId;
typedef gsize GumThreadId;
typedef struct _GumThreadDetails GumThreadDetails;
typedef struct _GumThreadEntrypoint GumThreadEntrypoint;
typedef struct _GumMallocRangeDetails GumMallocRangeDetails;

typedef enum {
  GUM_TEARDOWN_REQUIREMENT_FULL,
  GUM_TEARDOWN_REQUIREMENT_MINIMAL
} GumTeardownRequirement;

typedef enum {
  GUM_CODE_SIGNING_OPTIONAL,
  GUM_CODE_SIGNING_REQUIRED
} GumCodeSigningPolicy;

typedef enum {
  GUM_MODIFY_THREAD_FLAGS_NONE         = 0,
  GUM_MODIFY_THREAD_FLAGS_ABORT_SAFELY = (1 << 0),
} GumModifyThreadFlags;

typedef enum {
  GUM_THREAD_FLAGS_NAME                 = (1 << 0),
  GUM_THREAD_FLAGS_STATE                = (1 << 1),
  GUM_THREAD_FLAGS_CPU_CONTEXT          = (1 << 2),
  GUM_THREAD_FLAGS_ENTRYPOINT_ROUTINE   = (1 << 3),
  GUM_THREAD_FLAGS_ENTRYPOINT_PARAMETER = (1 << 4),

  GUM_THREAD_FLAGS_NONE                 = 0,
  GUM_THREAD_FLAGS_ALL                  = GUM_THREAD_FLAGS_NAME |
                                          GUM_THREAD_FLAGS_STATE |
                                          GUM_THREAD_FLAGS_CPU_CONTEXT |
                                          GUM_THREAD_FLAGS_ENTRYPOINT_ROUTINE |
                                          GUM_THREAD_FLAGS_ENTRYPOINT_PARAMETER,
} GumThreadFlags;

typedef enum {
  GUM_THREAD_RUNNING = 1,
  GUM_THREAD_STOPPED,
  GUM_THREAD_WAITING,
  GUM_THREAD_UNINTERRUPTIBLE,
  GUM_THREAD_HALTED
} GumThreadState;

struct _GumThreadEntrypoint
{
  GumAddress routine;
  GumAddress parameter;
};

struct _GumThreadDetails
{
  GumThreadFlags flags;
  GumThreadId id;
  const gchar * name;
  GumThreadState state;
  GumCpuContext cpu_context;
  GumThreadEntrypoint entrypoint;
};

typedef enum {
  GUM_WATCH_READ  = (1 << 0),
  GUM_WATCH_WRITE = (1 << 1),
} GumWatchConditions;

struct _GumMallocRangeDetails
{
  const GumMemoryRange * range;
};

typedef void (* GumModifyThreadFunc) (GumThreadId thread_id,
    GumCpuContext * cpu_context, gpointer user_data);
typedef gboolean (* GumFoundThreadFunc) (const GumThreadDetails * details,
    gpointer user_data);
typedef gboolean (* GumFoundModuleFunc) (GumModule * module,
    gpointer user_data);
typedef gboolean (* GumFoundMallocRangeFunc) (
    const GumMallocRangeDetails * details, gpointer user_data);

GUM_API GumOS gum_process_get_native_os (void);
GUM_API GumTeardownRequirement gum_process_get_teardown_requirement (void);
GUM_API void gum_process_set_teardown_requirement (
    GumTeardownRequirement requirement);
GUM_API GumCodeSigningPolicy gum_process_get_code_signing_policy (void);
GUM_API void gum_process_set_code_signing_policy (GumCodeSigningPolicy policy);
GUM_API gboolean gum_process_is_debugger_attached (void);
GUM_API GumProcessId gum_process_get_id (void);
GUM_API GumThreadId gum_process_get_current_thread_id (void);
GUM_API gboolean gum_process_has_thread (GumThreadId thread_id);
GUM_API GumThreadDetails * gum_process_find_thread_by_id (GumThreadId thread_id,
    GumThreadFlags flags);
GUM_API gboolean gum_process_modify_thread (GumThreadId thread_id,
    GumModifyThreadFunc func, gpointer user_data, GumModifyThreadFlags flags);
GUM_API void gum_process_enumerate_threads (GumFoundThreadFunc func,
    gpointer user_data, GumThreadFlags flags);
GUM_API GumModule * gum_process_get_main_module (void);
GUM_API GumModule * gum_process_get_libc_module (void);
GUM_API GumModule * gum_process_find_module_by_name (const gchar * name);
GUM_API GumModule * gum_process_find_module_by_address (GumAddress address);
GUM_API gboolean gum_process_find_function_range (gconstpointer address,
    GumMemoryRange * range);
GUM_API void gum_process_enumerate_modules (GumFoundModuleFunc func,
    gpointer user_data);
GUM_API void gum_process_enumerate_ranges (GumPageProtection prot,
    GumFoundRangeFunc func, gpointer user_data);
GUM_API void gum_process_enumerate_malloc_ranges (
    GumFoundMallocRangeFunc func, gpointer user_data);
GUM_API guint gum_thread_try_get_ranges (GumMemoryRange * ranges,
    guint max_length);
GUM_API gint gum_thread_get_system_error (void);
GUM_API void gum_thread_set_system_error (gint value);
GUM_API gboolean gum_thread_suspend (GumThreadId thread_id, GError ** error);
GUM_API gboolean gum_thread_resume (GumThreadId thread_id, GError ** error);
GUM_API gboolean gum_thread_set_hardware_breakpoint (GumThreadId thread_id,
    guint breakpoint_id, GumAddress address, GError ** error);
GUM_API gboolean gum_thread_unset_hardware_breakpoint (GumThreadId thread_id,
    guint breakpoint_id, GError ** error);
GUM_API gboolean gum_thread_set_hardware_watchpoint (GumThreadId thread_id,
    guint watchpoint_id, GumAddress address, gsize size, GumWatchConditions wc,
    GError ** error);
GUM_API gboolean gum_thread_unset_hardware_watchpoint (GumThreadId thread_id,
    guint watchpoint_id, GError ** error);

GUM_API const gchar * gum_code_signing_policy_to_string (
    GumCodeSigningPolicy policy);

GUM_API GType gum_thread_details_get_type (void) G_GNUC_CONST;
GUM_API GumThreadDetails * gum_thread_details_copy (
    const GumThreadDetails * details);
GUM_API void gum_thread_details_free (GumThreadDetails * details);

G_END_DECLS

#endif


#define GUM_IC_GET_THREAD_DATA(context, data_type) \
    ((data_type *) gum_invocation_context_get_listener_thread_data (context, \
        sizeof (data_type)))
#define GUM_IC_GET_FUNC_DATA(context, data_type) \
    ((data_type) gum_invocation_context_get_listener_function_data (context))
#define GUM_IC_GET_INVOCATION_DATA(context, data_type) \
    ((data_type *) \
        gum_invocation_context_get_listener_invocation_data (context,\
            sizeof (data_type)))

#define GUM_IC_GET_REPLACEMENT_DATA(ctx, data_type) \
    ((data_type) gum_invocation_context_get_replacement_data (ctx))

typedef struct _GumInvocationBackend GumInvocationBackend;
typedef struct _GumInvocationContext GumInvocationContext;
typedef guint GumPointCut;

struct _GumInvocationBackend
{
  GumPointCut (* get_point_cut) (GumInvocationContext * context);

  GumThreadId (* get_thread_id) (GumInvocationContext * context);
  guint (* get_depth) (GumInvocationContext * context);

  gpointer (* get_listener_thread_data) (GumInvocationContext * context,
      gsize required_size);
  gpointer (* get_listener_function_data) (GumInvocationContext * context);
  gpointer (* get_listener_invocation_data) (
      GumInvocationContext * context, gsize required_size);

  gpointer (* get_replacement_data) (GumInvocationContext * context);

  gpointer state;
  gpointer data;
};

struct _GumInvocationContext
{
  gpointer function;
  GumCpuContext * cpu_context;
  gint system_error;

  /*< private */
  GumInvocationBackend * backend;
};

enum _GumPointCut
{
  GUM_POINT_ENTER,
  GUM_POINT_LEAVE
};

G_BEGIN_DECLS

GUM_API GumPointCut gum_invocation_context_get_point_cut (
    GumInvocationContext * context);

GUM_API gpointer gum_invocation_context_get_nth_argument (
    GumInvocationContext * context, guint n);
GUM_API void gum_invocation_context_replace_nth_argument (
    GumInvocationContext * context, guint n, gpointer value);
GUM_API gpointer gum_invocation_context_get_return_value (
    GumInvocationContext * context);
GUM_API void gum_invocation_context_replace_return_value (
    GumInvocationContext * context, gpointer value);

GUM_API gpointer gum_invocation_context_get_return_address (
    GumInvocationContext * context);

GUM_API guint gum_invocation_context_get_thread_id (
    GumInvocationContext * context);
GUM_API guint gum_invocation_context_get_depth (
    GumInvocationContext * context);

GUM_API gpointer gum_invocation_context_get_listener_thread_data (
    GumInvocationContext * context, gsize required_size);
GUM_API gpointer gum_invocation_context_get_listener_function_data (
    GumInvocationContext * context);
GUM_API gpointer gum_invocation_context_get_listener_invocation_data (
    GumInvocationContext * context, gsize required_size);

GUM_API gpointer gum_invocation_context_get_replacement_data (
    GumInvocationContext * context);

G_END_DECLS

#endif

G_BEGIN_DECLS

typedef struct _GumInvocationListener GumInvocationListener;
typedef struct _GumInvocationListenerInterface GumInvocationListenerInterface;

typedef void (* GumInvocationCallback) (GumInvocationContext * context,
    gpointer user_data);

struct _GumInvocationListenerInterface
{
  void (* on_enter) (GumInvocationListener * self,
      GumInvocationContext * context);
  void (* on_leave) (GumInvocationListener * self,
      GumInvocationContext * context);
};

/*
 * Plain-C replacement for the former GObject interface: every listener
 * instance begins with this header (vtable + refcount). Implementers embed a
 * GumInvocationListener as their first member and call
 * gum_invocation_listener_init.
 */
struct _GumInvocationListener
{
  const GumInvocationListenerInterface * iface;
  gint ref_count;
  GDestroyNotify finalize;   /* per-instance cleanup; may be NULL */
};

/* Compatibility cast (was a GObject type-check macro in frida). */
#define GUM_INVOCATION_LISTENER(obj) ((GumInvocationListener *) (obj))

GUM_API void gum_invocation_listener_init (GumInvocationListener * self,
    const GumInvocationListenerInterface * iface, GDestroyNotify finalize);

GUM_API GumInvocationListener * gum_make_call_listener (
    GumInvocationCallback on_enter, GumInvocationCallback on_leave,
    gpointer data, GDestroyNotify data_destroy);
GUM_API GumInvocationListener * gum_make_probe_listener (
    GumInvocationCallback on_hit, gpointer data, GDestroyNotify data_destroy);

GUM_API GumInvocationListener * gum_invocation_listener_ref (
    GumInvocationListener * self);
GUM_API void gum_invocation_listener_unref (GumInvocationListener * self);

GUM_API void gum_invocation_listener_on_enter (GumInvocationListener * self,
    GumInvocationContext * context);
GUM_API void gum_invocation_listener_on_leave (GumInvocationListener * self,
    GumInvocationContext * context);

G_END_DECLS

#endif


G_BEGIN_DECLS

typedef struct _GumInterceptor GumInterceptor;

GUM_API GumInterceptor * gum_interceptor_ref (GumInterceptor * self);
GUM_API void gum_interceptor_unref (GumInterceptor * self);

typedef GArray GumInvocationStack;
typedef guint GumInvocationState;
typedef void (* GumInterceptorLockedFunc) (gpointer user_data);

typedef enum {
  GUM_INTERCEPTOR_SCENARIO_DEFAULT,
  GUM_INTERCEPTOR_SCENARIO_ONLINE,
  GUM_INTERCEPTOR_SCENARIO_OFFLINE,
} GumInterceptorScenario;

typedef enum {
  GUM_INVOCATION_IGNORABLE,
  GUM_INVOCATION_UNIGNORABLE,
} GumInvocationIgnorability;

typedef enum _GumRedirectWriteResult {
  GUM_REDIRECT_WRITTEN,
  GUM_REDIRECT_DECLINED,
} GumRedirectWriteResult;

typedef struct _GumInterceptorOptions GumInterceptorOptions;
typedef struct _GumAttachOptions GumAttachOptions;
typedef struct _GumReplaceOptions GumReplaceOptions;
typedef struct _GumRedirectWriteDetails GumRedirectWriteDetails;

typedef GumRedirectWriteResult (* GumWriteRedirectFunc) (
    const GumRedirectWriteDetails * details, gpointer user_data);

struct _GumInterceptorOptions
{
  gint scratch_register;
  GumInterceptorScenario scenario;
  GumRelocationPolicy relocation_policy;
  GumWriteRedirectFunc write_redirect;
  gpointer write_redirect_data;
  guint redirect_space_hint;
};

struct _GumAttachOptions
{
  GumInterceptorOptions instrumentation;
  gpointer listener_function_data;
  GumInvocationIgnorability ignorability;
};

struct _GumReplaceOptions
{
  GumInterceptorOptions instrumentation;
  gpointer replacement_data;
};

struct _GumRedirectWriteDetails
{
  gpointer writer;
  gpointer target;
  gint scratch_register;
  guint capacity;
};

typedef enum
{
  GUM_ATTACH_OK               =  0,
  GUM_ATTACH_WRONG_SIGNATURE  = -1,
  GUM_ATTACH_ALREADY_ATTACHED = -2,
  GUM_ATTACH_POLICY_VIOLATION = -3,
  GUM_ATTACH_WRONG_TYPE       = -4,
} GumAttachReturn;

typedef enum
{
  GUM_REPLACE_OK               =  0,
  GUM_REPLACE_WRONG_SIGNATURE  = -1,
  GUM_REPLACE_ALREADY_REPLACED = -2,
  GUM_REPLACE_POLICY_VIOLATION = -3,
  GUM_REPLACE_WRONG_TYPE       = -4,
} GumReplaceReturn;

GUM_API GumInterceptor * gum_interceptor_obtain (void);

GUM_API void gum_interceptor_set_default_options (GumInterceptor * self,
    const GumInterceptorOptions * options);

GUM_API GumAttachReturn gum_interceptor_attach (GumInterceptor * self,
    gpointer target, GumInvocationListener * listener,
    const GumAttachOptions * options);
GUM_API void gum_interceptor_detach (GumInterceptor * self,
    GumInvocationListener * listener);

GUM_API GumReplaceReturn gum_interceptor_replace (GumInterceptor * self,
    gpointer function_address, gpointer replacement_function,
    gpointer * original_function, const GumReplaceOptions * options);
GumReplaceReturn gum_interceptor_replace_fast (GumInterceptor * self,
    gpointer function_address, gpointer replacement_function,
    gpointer * original_function, const GumInterceptorOptions * options);
GUM_API void gum_interceptor_revert (GumInterceptor * self,
    gpointer target);

GUM_API void gum_interceptor_begin_transaction (GumInterceptor * self);
GUM_API void gum_interceptor_end_transaction (GumInterceptor * self);
GUM_API gboolean gum_interceptor_flush (GumInterceptor * self);
GUM_API gboolean gum_interceptor_flush_function (GumInterceptor * self,
    gconstpointer function_address);
GUM_API gboolean gum_interceptor_flush_listener (GumInterceptor * self,
    GumInvocationListener * listener);

GUM_API GumInvocationContext * gum_interceptor_get_current_invocation (void);
GUM_API GumInvocationContext * gum_interceptor_get_live_replacement_invocation (
    gpointer replacement_function);
GUM_API GumInvocationStack * gum_interceptor_get_current_stack (void);

GUM_API void gum_interceptor_ignore_current_thread (GumInterceptor * self);
GUM_API void gum_interceptor_unignore_current_thread (GumInterceptor * self);
GUM_API gboolean gum_interceptor_maybe_unignore_current_thread (
    GumInterceptor * self);

GUM_API void gum_interceptor_ignore_other_threads (GumInterceptor * self);
GUM_API void gum_interceptor_unignore_other_threads (GumInterceptor * self);

GUM_API gpointer gum_invocation_stack_translate (GumInvocationStack * self,
    gpointer return_address);

GUM_API void gum_interceptor_save (GumInvocationState * state);
GUM_API void gum_interceptor_restore (GumInvocationState * state);

GUM_API void gum_interceptor_with_lock_held (GumInterceptor * self,
    GumInterceptorLockedFunc func, gpointer user_data);
GUM_API gboolean gum_interceptor_is_locked (GumInterceptor * self);

GUM_API gsize gum_interceptor_detect_hook_size (gconstpointer code,
    csh capstone, cs_insn * insn);

G_END_DECLS

#endif
/* ==== inlined header: gumreturnaddress.h ==== */
/*
 * Copyright (C) 2008-2010 Ole André Vadla Ravnås <oleavr@nowsecure.com>
 *
 * Licence: wxWindows Library Licence, Version 3.1
 */

#ifndef __GUM_RETURN_ADDRESS_H__
#define __GUM_RETURN_ADDRESS_H__


typedef struct _GumReturnAddressDetails GumReturnAddressDetails;
typedef gpointer GumReturnAddress;
typedef struct _GumReturnAddressArray GumReturnAddressArray;

struct _GumReturnAddressDetails
{
  GumReturnAddress address;
  gchar module_name[GUM_MAX_PATH + 1];
  gchar function_name[GUM_MAX_SYMBOL_NAME + 1];
  gchar file_name[GUM_MAX_PATH + 1];
  guint line_number;
  guint column;
};

struct _GumReturnAddressArray
{
  guint len;
  GumReturnAddress items[GUM_MAX_BACKTRACE_DEPTH];
};

G_BEGIN_DECLS

GUM_API gboolean gum_return_address_details_from_address (
    GumReturnAddress address, GumReturnAddressDetails * details);

GUM_API gboolean gum_return_address_array_is_equal (
    const GumReturnAddressArray * array1,
    const GumReturnAddressArray * array2);

G_END_DECLS

#endif

G_BEGIN_DECLS

GUM_API void gum_init (void);
GUM_API void gum_shutdown (void);
GUM_API void gum_deinit (void);

GUM_API void gum_init_embedded (void);
GUM_API void gum_deinit_embedded (void);

GUM_API void gum_prepare_to_fork (void);
GUM_API void gum_recover_from_fork_in_parent (void);
GUM_API void gum_recover_from_fork_in_child (void);

G_END_DECLS

#endif
